//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class StripeExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> AddStripe(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> apiKey) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> WithApiKey(this ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> apiKey) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> WithListen(this ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.IResourceWithEndpoints> forwardTo, string webhookPath = "/webhooks/stripe", System.Collections.Generic.IEnumerable<string>? events = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> WithListen(this ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> builder, ApplicationModel.IResourceBuilder<ExternalServiceResource> forwardTo, string webhookPath = "/webhooks/stripe", System.Collections.Generic.IEnumerable<string>? events = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<TDestination> WithReference<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.StripeResource> source, string webhookSigningSecretEnvVarName = "STRIPE_WEBHOOK_SECRET")
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class StripeResource : ContainerResource
    {
        public StripeResource(string name) : base(default!, default) { }

        public string? WebhookSigningSecret { get { throw null; } }
    }
}