//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class ListmonkBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> AddListmonk(this IDistributedApplicationBuilder builder, string name, int? port = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithAdminCredentials(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string username, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> password) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithAdminPassword(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> password) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithAdminUser(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string username) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithAppAddress(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string address) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithDatabaseMaxIdleConnections(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, int maxIdle) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithDatabaseMaxLifetime(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string maxLifetime) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithDatabaseMaxOpenConnections(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, int maxOpen) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithDatabaseParameters(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string parameters) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithDatabaseSslMode(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string sslMode) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithGroupId(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, int groupId) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithReference(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresDatabaseResource> database) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithTimeZone(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string timeZone) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithUploadsBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string source) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithUploadsVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> WithUserId(this ApplicationModel.IResourceBuilder<ApplicationModel.ListmonkResource> builder, int userId) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class ListmonkResource : ContainerResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public ListmonkResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}