//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class LavinMQHostingExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LavinMQContainerResource> AddLavinMQ(this IDistributedApplicationBuilder builder, string name, int amqpPort = 5672, int managementPort = 15672) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.LavinMQContainerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.LavinMQContainerResource> builder, string source, bool isReadOnly = false) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.LavinMQContainerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.LavinMQContainerResource> builder, string name, bool isReadOnly = false) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class LavinMQContainerResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public LavinMQContainerResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }
    }
}