//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class BitwardenSecretManagerExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> AddBitwardenSecretManager(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> projectNameOrId, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> organizationId, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> accessToken) { throw null; }

        [AspireExport("addSecretWithRemoteName")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string name, string remoteName) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> AddSecret(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IExpressionValue AsSecretId(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> secret) { throw null; }

        [AspireExport("getSecretById")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> GetSecret(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string name, System.Guid secretId) { throw null; }

        [AspireExport("getSecretWithRemoteName")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> GetSecret(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string name, string remoteName) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretResource> GetSecret(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string name) { throw null; }

        [AspireExportIgnore(Reason = "EndpointReference is not ATS-compatible; polyglot apphosts use the string variant")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithApiUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.EndpointReference endpoint) { throw null; }

        [AspireExport("withApiUrlFromParameter")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithApiUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> apiUrl) { throw null; }

        [AspireExport("withApiUrlFromExternalService")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithApiUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.IResourceBuilder<ExternalServiceResource> server) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithApiUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string apiUrl) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithAuthCacheDirectory(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string authCacheDirectory) { throw null; }

        [AspireExport("withBitwardenReferenceAccessToken")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAccessToken<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> source, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> accessToken)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExportIgnore(Reason = "Use the source-based overload for the common case; this overload is for the edge case of a custom connection name passed to WithReference")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAccessToken<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, string connectionName, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> accessToken)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExport("withBitwardenReferenceAuthCacheDirectoryFromParameter")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheDirectory<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> source, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> authCacheDirectory)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExport("withBitwardenReferenceAuthCacheDirectory")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheDirectory<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> source, string authCacheDirectory)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExportIgnore(Reason = "Use the source-based overload for the common case; this overload is for the edge case of a custom connection name passed to WithReference")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheDirectory<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, string connectionName, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> authCacheDirectory)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExportIgnore(Reason = "Use the source-based overload for the common case; this overload is for the edge case of a custom connection name passed to WithReference")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheDirectory<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, string connectionName, string authCacheDirectory)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExport("withBitwardenReferenceAuthCacheVolume")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheVolume<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> source, string? volumeName = null, string containerDirectory = "/var/lib/bitwarden")
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExportIgnore(Reason = "Use the source-based overload for the common case; this overload is for the edge case of a custom connection name passed to WithReference")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithBitwardenAuthCacheVolume<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, string connectionName, string? volumeName = null, string containerDirectory = "/var/lib/bitwarden")
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithCacheFile(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string cacheFile) { throw null; }

        [AspireExportIgnore(Reason = "EndpointReference is not ATS-compatible; polyglot apphosts use the string variant")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithIdentityUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.EndpointReference endpoint) { throw null; }

        [AspireExport("withIdentityUrlFromParameter")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithIdentityUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> identityUrl) { throw null; }

        [AspireExport("withIdentityUrlFromExternalService")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithIdentityUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, ApplicationModel.IResourceBuilder<ExternalServiceResource> server) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> WithIdentityUrl(this ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> builder, string identityUrl) { throw null; }

        [AspireExport("withBitwardenSecretManagerReference")]
        public static ApplicationModel.IResourceBuilder<TDestination> WithReference<TDestination>(this ApplicationModel.IResourceBuilder<TDestination> builder, ApplicationModel.IResourceBuilder<ApplicationModel.BitwardenSecretManagerResource> source, string? connectionName = null)
            where TDestination : ApplicationModel.IResourceWithEnvironment { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport]
    public partial class BitwardenSecretManagerResource : Resource, IResourceWithWaitSupport, IResource
    {
        public BitwardenSecretManagerResource(string name, ParameterResource projectNameOrIdParameter, ParameterResource organizationIdParameter, ParameterResource managementAccessToken, string appHostDirectory) : base(default!) { }

        public string? AuthCacheDirectory { get { throw null; } }

        public string? CacheFile { get { throw null; } }

        public System.Guid? ExistingProjectId { get { throw null; } }

        public System.Guid? ProjectId { get { throw null; } }
    }

    [AspireExport]
    public partial class BitwardenSecretResource : ParameterResource, IResourceWithParent<BitwardenSecretManagerResource>, IResourceWithParent, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public BitwardenSecretResource(string name, string remoteName, BitwardenSecretManagerResource parent, System.Func<ParameterDefault?, string> valueGetter) : base(default!, default!, default) { }

        string IManifestExpressionProvider.ValueExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<object> IValueWithReferences.References { get { throw null; } }

        public bool IsManaged { get { throw null; } }

        public BitwardenSecretManagerResource Parent { get { throw null; } }

        public string RemoteName { get { throw null; } }

        public System.Guid? ResolvedSecretId { get { throw null; } }

        public System.Guid? SecretId { get { throw null; } }

        System.Threading.Tasks.ValueTask<string?> IValueProvider.GetValueAsync(ValueProviderContext context, System.Threading.CancellationToken cancellationToken) { throw null; }

        System.Threading.Tasks.ValueTask<string?> IValueProvider.GetValueAsync(System.Threading.CancellationToken cancellationToken) { throw null; }
    }
}