//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.Meilisearch
{
    public sealed partial class MeilisearchClientSettings
    {
        public bool DisableHealthChecks { get { throw null; } set { } }

        public System.Uri? Endpoint { get { throw null; } set { } }

        public int? HealthCheckTimeout { get { throw null; } set { } }

        public string? MasterKey { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireMeilisearchExtensions
    {
        public static void AddKeyedMeilisearchClient(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.Meilisearch.MeilisearchClientSettings>? configureSettings = null) { }

        public static void AddMeilisearchClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.Meilisearch.MeilisearchClientSettings>? configureSettings = null) { }
    }
}