//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class NgrokExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> AddNgrok(this IDistributedApplicationBuilder builder, string name, string? configurationFolder = null, int? endpointPort = null, string? endpointName = null, int? configurationVersion = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> WithAuthToken(this ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> ngrokAuthToken) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> WithAuthToken(this ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> builder, string ngrokAuthToken) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> WithTunnelEndpoint<TResource>(this ApplicationModel.IResourceBuilder<ApplicationModel.NgrokResource> builder, ApplicationModel.IResourceBuilder<TResource> resource, string endpointName, string? ngrokUrl = null, System.Collections.Generic.IDictionary<string, string>? labels = null)
            where TResource : ApplicationModel.IResourceWithEndpoints { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial record NgrokEndpoint(string EndpointName, string? Url, System.Collections.Generic.IDictionary<string, string>? Labels = null)
    {
    }

    public sealed partial record NgrokEndpointAnnotation(IResourceWithEndpoints Resource) : IResourceAnnotation
    {
        public System.Collections.Generic.ICollection<NgrokEndpoint> Endpoints { get { throw null; } }
    }

    public partial class NgrokResource : ContainerResource
    {
        public NgrokResource(string name) : base(default!, default) { }
    }
}