//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.Posta.Clients
{
    public partial interface IPostaClient
    {
        IPostaEmailsClient Emails { get; }

        Endpoints.IPostaEndpoints Endpoints { get; }

        IPostaHealthClient Health { get; }

        IPostaInfoClient Info { get; }

        IPostaSubscriberListsClient SubscriberLists { get; }

        IPostaTemplatesClient Templates { get; }
    }

    public partial interface IPostaEmailsClient : IPostaSectionClient
    {
        System.Threading.Tasks.Task<Models.Emails.GetEmailDeliveryStatusResponse?> GetEmailDeliveryStatusAsync(Models.Emails.GetEmailDeliveryStatusRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.GetEmailDetailsResponse?> GetEmailDetailsAsync(Models.Emails.GetEmailDetailsRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.PreviewEmailFromTemplateResponse?> PreviewEmailFromTemplateAsync(Models.Emails.PreviewEmailFromTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.RetryFailedEmailResponse?> RetryFailedEmailAsync(Models.Emails.RetryFailedEmailRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.SendAnEmailResponse?> SendAnEmailAsync(Models.Emails.SendAnEmailRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.SendBatchEmailsResponse?> SendBatchEmailsAsync(Models.Emails.SendBatchEmailsRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.SendEmailUsingTemplateResponse?> SendEmailUsingTemplateAsync(Models.Emails.SendEmailUsingTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Emails.VerifyAnEmailAddressResponse?> VerifyAnEmailAddressAsync(Models.Emails.VerifyAnEmailAddressRequest request, System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IPostaHealthClient : IPostaSectionClient
    {
        System.Threading.Tasks.Task<Models.Health.LivenessProbeResponse?> LivenessProbeAsync(System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Health.ReadinessProbeResponse?> ReadinessProbeAsync(System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IPostaInfoClient : IPostaSectionClient
    {
        System.Threading.Tasks.Task<Models.Info.ApplicationInfoResponse?> ApplicationInfoAsync(System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IPostaSectionClient
    {
        System.Threading.Tasks.Task<System.Text.Json.JsonDocument?> SendAsync(Endpoints.PostaEndpoint endpoint, Transport.PostaRequest? request = null, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<TResponse?> SendAsync<TResponse>(Endpoints.PostaEndpoint endpoint, Transport.PostaRequest? request = null, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Transport.PostaStreamResponse> SendStreamAsync(Endpoints.PostaEndpoint endpoint, Transport.PostaRequest? request = null, System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IPostaSubscriberListsClient : IPostaSectionClient
    {
        System.Threading.Tasks.Task<Models.SubscriberLists.ReSubscribeAnEmailToAListResponse?> ReSubscribeAnEmailToAListAsync(Models.SubscriberLists.ReSubscribeAnEmailToAListRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.SubscriberLists.SubscribeAnEmailToAListResponse?> SubscribeAnEmailToAListAsync(Models.SubscriberLists.SubscribeAnEmailToAListRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.SubscriberLists.UnsubscribeAnEmailFromAListResponse?> UnsubscribeAnEmailFromAListAsync(Models.SubscriberLists.UnsubscribeAnEmailFromAListRequest request, System.Threading.CancellationToken cancellationToken = default);
    }

    public partial interface IPostaTemplatesClient : IPostaSectionClient
    {
        System.Threading.Tasks.Task<Models.Templates.CreateTemplateResponse?> CreateTemplateAsync(Models.Templates.CreateTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.DeleteTemplateResponse?> DeleteTemplateAsync(Models.Templates.DeleteTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.GetTemplateResponse?> GetTemplateAsync(Models.Templates.GetTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.ListTemplatesResponse?> ListTemplatesAsync(Models.Templates.ListTemplatesRequest? request = null, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.PreviewTemplateResponse?> PreviewTemplateAsync(Models.Templates.PreviewTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.SendTestEmailResponse?> SendTestEmailAsync(Models.Templates.SendTestEmailRequest request, System.Threading.CancellationToken cancellationToken = default);
        System.Threading.Tasks.Task<Models.Templates.UpdateTemplateResponse?> UpdateTemplateAsync(Models.Templates.UpdateTemplateRequest request, System.Threading.CancellationToken cancellationToken = default);
    }
}

namespace CommunityToolkit.Aspire.Posta.Configuration
{
    public partial interface IPostaCredentialProvider
    {
        System.Threading.Tasks.ValueTask<string?> GetCredentialAsync(Endpoints.PostaAuthentication authentication, System.Threading.CancellationToken cancellationToken = default);
    }

    public sealed partial class PostaClientSettings
    {
        public string? AccessToken { get { throw null; } set { } }

        public string? ApiKey { get { throw null; } set { } }

        public System.Uri? Endpoint { get { throw null; } set { } }

        public System.TimeSpan Timeout { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Endpoints
{
    public partial interface IPostaEndpoints
    {
        PostaEndpoint ApplicationInfo { get; }

        PostaEndpoint CreateTemplate { get; }

        PostaEndpoint DeleteTemplate { get; }

        PostaEndpoint GetEmailDeliveryStatus { get; }

        PostaEndpoint GetEmailDetails { get; }

        PostaEndpoint GetTemplate { get; }

        PostaEndpoint ListTemplates { get; }

        PostaEndpoint LivenessProbe { get; }

        PostaEndpoint PreviewEmailFromTemplate { get; }

        PostaEndpoint PreviewTemplate { get; }

        PostaEndpoint ReadinessProbe { get; }

        PostaEndpoint ReSubscribeAnEmailToAList { get; }

        PostaEndpoint RetryFailedEmail { get; }

        PostaEndpoint SendAnEmail { get; }

        PostaEndpoint SendBatchEmails { get; }

        PostaEndpoint SendEmailUsingTemplate { get; }

        PostaEndpoint SendTestEmail { get; }

        PostaEndpoint SubscribeAnEmailToAList { get; }

        PostaEndpoint UnsubscribeAnEmailFromAList { get; }

        PostaEndpoint UpdateTemplate { get; }

        PostaEndpoint VerifyAnEmailAddress { get; }
    }

    public enum PostaAuthentication
    {
        None = 0,
        ApiKey = 1,
        AccessToken = 2
    }

    public sealed partial record PostaEndpoint(System.Net.Http.HttpMethod Method, string Path, PostaAuthentication Authentication, bool IsImplemented = true, string? Documentation = null)
    {
    }

    public partial class PostaEndpoints : IPostaEndpoints
    {
        public virtual PostaEndpoint ApplicationInfo { get { throw null; } }

        public virtual PostaEndpoint CreateTemplate { get { throw null; } }

        public virtual PostaEndpoint DeleteTemplate { get { throw null; } }

        public virtual PostaEndpoint GetEmailDeliveryStatus { get { throw null; } }

        public virtual PostaEndpoint GetEmailDetails { get { throw null; } }

        public virtual PostaEndpoint GetTemplate { get { throw null; } }

        public virtual PostaEndpoint ListTemplates { get { throw null; } }

        public virtual PostaEndpoint LivenessProbe { get { throw null; } }

        public virtual PostaEndpoint PreviewEmailFromTemplate { get { throw null; } }

        public virtual PostaEndpoint PreviewTemplate { get { throw null; } }

        public virtual PostaEndpoint ReadinessProbe { get { throw null; } }

        public virtual PostaEndpoint ReSubscribeAnEmailToAList { get { throw null; } }

        public virtual PostaEndpoint RetryFailedEmail { get { throw null; } }

        public virtual PostaEndpoint SendAnEmail { get { throw null; } }

        public virtual PostaEndpoint SendBatchEmails { get { throw null; } }

        public virtual PostaEndpoint SendEmailUsingTemplate { get { throw null; } }

        public virtual PostaEndpoint SendTestEmail { get { throw null; } }

        public virtual PostaEndpoint SubscribeAnEmailToAList { get { throw null; } }

        public virtual PostaEndpoint UnsubscribeAnEmailFromAList { get { throw null; } }

        public virtual PostaEndpoint UpdateTemplate { get { throw null; } }

        public virtual PostaEndpoint VerifyAnEmailAddress { get { throw null; } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.Emails
{
    public partial class GetEmailDeliveryStatusRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public required string Id { get { throw null; } set { } }
    }

    public partial class GetEmailDeliveryStatusResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.GetEmailDeliveryStatusResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class GetEmailDetailsRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public required string Id { get { throw null; } set { } }
    }

    public partial class GetEmailDetailsResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.GetEmailDetailsResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class PreviewEmailFromTemplateRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template")]
        public string? Template { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_data")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? TemplateData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }
    }

    public partial class PreviewEmailFromTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.PreviewEmailFromTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class RetryFailedEmailRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public required string Id { get { throw null; } set { } }
    }

    public partial class RetryFailedEmailResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.RetryFailedEmailResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class SendAnEmailRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("attachments")]
        public System.Collections.Generic.IReadOnlyList<Shared.SendAnEmailRequestAttachmentsItem>? Attachments { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public bool? DryRun { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("from")]
        public required string From { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("headers")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? Headers { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html")]
        public string? Html { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_unsubscribe_post")]
        public bool? ListUnsubscribePost { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_unsubscribe_url")]
        public string? ListUnsubscribeUrl { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("send_at")]
        public System.DateTimeOffset? SendAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public required string Subject { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string? Text { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("to")]
        public required System.Collections.Generic.IReadOnlyList<string> To { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("unsubscribe")]
        public Shared.SendAnEmailRequestUnsubscribe? Unsubscribe { get { throw null; } set { } }
    }

    public partial class SendAnEmailResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.SendAnEmailResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public bool? DryRun { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("from")]
        public string? From { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("recipients")]
        public required System.Collections.Generic.IReadOnlyList<Shared.SendBatchEmailsRequestRecipientsItem> Recipients { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template")]
        public string? Template { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("unsubscribe")]
        public Shared.SendBatchEmailsRequestUnsubscribe? Unsubscribe { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.SendBatchEmailsResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class SendEmailUsingTemplateRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("attachments")]
        public System.Collections.Generic.IReadOnlyList<Shared.SendEmailUsingTemplateRequestAttachmentsItem>? Attachments { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public bool? DryRun { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("from")]
        public string? From { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template")]
        public string? Template { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_data")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? TemplateData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("to")]
        public required System.Collections.Generic.IReadOnlyList<string> To { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("unsubscribe")]
        public Shared.SendEmailUsingTemplateRequestUnsubscribe? Unsubscribe { get { throw null; } set { } }
    }

    public partial class SendEmailUsingTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.SendEmailUsingTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class VerifyAnEmailAddressRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public required string Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public bool? Fresh { get { throw null; } set { } }
    }

    public partial class VerifyAnEmailAddressResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.VerifyAnEmailAddressResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.Health
{
    public partial class LivenessProbeResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class ReadinessProbeResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("database")]
        public string? Database { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis")]
        public string? Redis { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.Info
{
    public partial class ApplicationInfoResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.ApplicationInfoResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.Shared
{
    public partial class ApplicationInfoResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("commit_id")]
        public string? CommitId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("openapi_docs")]
        public bool? OpenapiDocs { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public string? Version { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("active_version")]
        public CreateTemplateResponseDataActiveVersion? ActiveVersion { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("active_version_id")]
        public int? ActiveVersionId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_by")]
        public CreateTemplateResponseDataCreatedBy? CreatedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by")]
        public CreateTemplateResponseDataLastEditedBy? LastEditedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by_id")]
        public int? LastEditedById { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseDataActiveVersion
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("localizations")]
        public System.Collections.Generic.IReadOnlyList<CreateTemplateResponseDataActiveVersionLocalizationsItem>? Localizations { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet")]
        public CreateTemplateResponseDataActiveVersionStylesheet? Stylesheet { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet_id")]
        public int? StylesheetId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int? Version { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseDataActiveVersionLocalizationsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("builder_json")]
        public string? BuilderJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html_template")]
        public string? HtmlTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject_template")]
        public string? SubjectTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_template")]
        public string? TextTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version_id")]
        public int? VersionId { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseDataActiveVersionStylesheet
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("css")]
        public string? Css { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseDataCreatedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponseDataLastEditedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class GetEmailDeliveryStatusResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public string? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("error_message")]
        public string? ErrorMessage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("retry_count")]
        public int? RetryCount { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sent_at")]
        public string? SentAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class GetEmailDetailsResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("api_key_id")]
        public int? ApiKeyId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("api_key_name")]
        public string? ApiKeyName { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("attachments_json")]
        public string? AttachmentsJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("error_message")]
        public string? ErrorMessage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("headers_json")]
        public string? HeadersJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html_body")]
        public string? HtmlBody { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_unsubscribe_mailto")]
        public string? ListUnsubscribeMailto { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_unsubscribe_post")]
        public bool? ListUnsubscribePost { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_unsubscribe_url")]
        public string? ListUnsubscribeUrl { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("provider")]
        public string? Provider { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("recipients")]
        public System.Collections.Generic.IReadOnlyList<string>? Recipients { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("retry_count")]
        public int? RetryCount { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("scheduled_at")]
        public System.DateTimeOffset? ScheduledAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sender")]
        public string? Sender { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sent_at")]
        public System.DateTimeOffset? SentAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("smtp_hostname")]
        public string? SmtpHostname { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string? Subject { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_name")]
        public string? TemplateName { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_body")]
        public string? TextBody { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("unsubscribe_list_id")]
        public int? UnsubscribeListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("uuid")]
        public string? Uuid { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("active_version")]
        public GetTemplateResponseDataActiveVersion? ActiveVersion { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("active_version_id")]
        public int? ActiveVersionId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_by")]
        public GetTemplateResponseDataCreatedBy? CreatedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by")]
        public GetTemplateResponseDataLastEditedBy? LastEditedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by_id")]
        public int? LastEditedById { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseDataActiveVersion
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("localizations")]
        public System.Collections.Generic.IReadOnlyList<GetTemplateResponseDataActiveVersionLocalizationsItem>? Localizations { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet")]
        public GetTemplateResponseDataActiveVersionStylesheet? Stylesheet { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet_id")]
        public int? StylesheetId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int? Version { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseDataActiveVersionLocalizationsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("builder_json")]
        public string? BuilderJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html_template")]
        public string? HtmlTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject_template")]
        public string? SubjectTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_template")]
        public string? TextTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version_id")]
        public int? VersionId { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseDataActiveVersionStylesheet
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("css")]
        public string? Css { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseDataCreatedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class GetTemplateResponseDataLastEditedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("active_version")]
        public ListTemplatesResponseDataItemActiveVersion? ActiveVersion { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("active_version_id")]
        public int? ActiveVersionId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_by")]
        public ListTemplatesResponseDataItemCreatedBy? CreatedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by")]
        public ListTemplatesResponseDataItemLastEditedBy? LastEditedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by_id")]
        public int? LastEditedById { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItemActiveVersion
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("localizations")]
        public System.Collections.Generic.IReadOnlyList<ListTemplatesResponseDataItemActiveVersionLocalizationsItem>? Localizations { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet")]
        public ListTemplatesResponseDataItemActiveVersionStylesheet? Stylesheet { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet_id")]
        public int? StylesheetId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int? Version { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItemActiveVersionLocalizationsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("builder_json")]
        public string? BuilderJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html_template")]
        public string? HtmlTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject_template")]
        public string? SubjectTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_template")]
        public string? TextTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version_id")]
        public int? VersionId { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItemActiveVersionStylesheet
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("css")]
        public string? Css { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItemCreatedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponseDataItemLastEditedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponsePageable
    {
        [System.Text.Json.Serialization.JsonPropertyName("current_page")]
        public int? CurrentPage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("empty")]
        public bool? Empty { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("size")]
        public int? Size { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("total_elements")]
        public long? TotalElements { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("total_pages")]
        public int? TotalPages { get { throw null; } set { } }
    }

    public partial class PreviewEmailFromTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("html")]
        public string? Html { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string? Subject { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string? Text { get { throw null; } set { } }
    }

    public partial class PreviewTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("html")]
        public string? Html { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject")]
        public string? Subject { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text")]
        public string? Text { get { throw null; } set { } }
    }

    public partial class ReSubscribeAnEmailToAListResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("action")]
        public string? Action { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_created")]
        public bool? ListCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("member_added")]
        public bool? MemberAdded { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_created")]
        public bool? SubscriberCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_id")]
        public int? SubscriberId { get { throw null; } set { } }
    }

    public partial class RetryFailedEmailResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class SendAnEmailRequestAttachmentsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public string? Content { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("content_type")]
        public string? ContentType { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("filename")]
        public string? Filename { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("storage_key")]
        public string? StorageKey { get { throw null; } set { } }
    }

    public partial class SendAnEmailRequestUnsubscribe
    {
        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("mailto")]
        public string? Mailto { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("one_click")]
        public bool? OneClick { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get { throw null; } set { } }
    }

    public partial class SendAnEmailResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsRequestRecipientsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public required string Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_data")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? TemplateData { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsRequestUnsubscribe
    {
        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("mailto")]
        public string? Mailto { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("one_click")]
        public bool? OneClick { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("failed")]
        public int? Failed { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("results")]
        public System.Collections.Generic.IReadOnlyList<SendBatchEmailsResponseDataResultsItem>? Results { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sent")]
        public int? Sent { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("skipped")]
        public int? Skipped { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("total")]
        public int? Total { get { throw null; } set { } }
    }

    public partial class SendBatchEmailsResponseDataResultsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("error")]
        public string? Error { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class SendEmailUsingTemplateRequestAttachmentsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("content")]
        public string? Content { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("content_type")]
        public string? ContentType { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("filename")]
        public string? Filename { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("storage_key")]
        public string? StorageKey { get { throw null; } set { } }
    }

    public partial class SendEmailUsingTemplateRequestUnsubscribe
    {
        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("mailto")]
        public string? Mailto { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("one_click")]
        public bool? OneClick { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("url")]
        public string? Url { get { throw null; } set { } }
    }

    public partial class SendEmailUsingTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class SendTestEmailResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public string? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }
    }

    public partial class SubscribeAnEmailToAListResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("action")]
        public string? Action { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_created")]
        public bool? ListCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("member_added")]
        public bool? MemberAdded { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_created")]
        public bool? SubscriberCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_id")]
        public int? SubscriberId { get { throw null; } set { } }
    }

    public partial class UnsubscribeAnEmailFromAListResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("action")]
        public string? Action { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_created")]
        public bool? ListCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list_id")]
        public int? ListId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("member_added")]
        public bool? MemberAdded { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_created")]
        public bool? SubscriberCreated { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subscriber_id")]
        public int? SubscriberId { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("active_version")]
        public UpdateTemplateResponseDataActiveVersion? ActiveVersion { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("active_version_id")]
        public int? ActiveVersionId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_by")]
        public UpdateTemplateResponseDataCreatedBy? CreatedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by")]
        public UpdateTemplateResponseDataLastEditedBy? LastEditedBy { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("last_edited_by_id")]
        public int? LastEditedById { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseDataActiveVersion
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("localizations")]
        public System.Collections.Generic.IReadOnlyList<UpdateTemplateResponseDataActiveVersionLocalizationsItem>? Localizations { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet")]
        public UpdateTemplateResponseDataActiveVersionStylesheet? Stylesheet { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet_id")]
        public int? StylesheetId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_id")]
        public int? TemplateId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version")]
        public int? Version { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseDataActiveVersionLocalizationsItem
    {
        [System.Text.Json.Serialization.JsonPropertyName("builder_json")]
        public string? BuilderJson { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("html_template")]
        public string? HtmlTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject_template")]
        public string? SubjectTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_template")]
        public string? TextTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("version_id")]
        public int? VersionId { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseDataActiveVersionStylesheet
    {
        [System.Text.Json.Serialization.JsonPropertyName("created_at")]
        public System.DateTimeOffset? CreatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("css")]
        public string? Css { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("updated_at")]
        public System.DateTimeOffset? UpdatedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("user_id")]
        public int? UserId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("workspace_id")]
        public int? WorkspaceId { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseDataCreatedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponseDataLastEditedBy
    {
        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public int? Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class VerifyAnEmailAddressResponseData
    {
        [System.Text.Json.Serialization.JsonPropertyName("cached")]
        public bool? Cached { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("checked_at")]
        public System.DateTimeOffset? CheckedAt { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("checks")]
        public VerifyAnEmailAddressResponseDataChecks? Checks { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public string? Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("mailbox_verified")]
        public bool? MailboxVerified { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("previously_bounced")]
        public bool? PreviouslyBounced { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string? Reason { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("score")]
        public int? Score { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("status")]
        public string? Status { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("suppressed")]
        public bool? Suppressed { get { throw null; } set { } }
    }

    public partial class VerifyAnEmailAddressResponseDataChecks
    {
        [System.Text.Json.Serialization.JsonPropertyName("disposable")]
        public bool? Disposable { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("mx")]
        public bool? Mx { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("role_account")]
        public bool? RoleAccount { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("smtp")]
        public string? Smtp { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("syntax")]
        public bool? Syntax { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.SubscriberLists
{
    public partial class ReSubscribeAnEmailToAListRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public required string Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }
    }

    public partial class ReSubscribeAnEmailToAListResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.ReSubscribeAnEmailToAListResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class SubscribeAnEmailToAListRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public required string Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("list")]
        public required string List { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }
    }

    public partial class SubscribeAnEmailToAListResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.SubscribeAnEmailToAListResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class UnsubscribeAnEmailFromAListRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("email")]
        public required string Email { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("reason")]
        public string? Reason { get { throw null; } set { } }
    }

    public partial class UnsubscribeAnEmailFromAListResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.UnsubscribeAnEmailFromAListResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Models.Templates
{
    public partial class CreateTemplateRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public required string Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }
    }

    public partial class CreateTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.CreateTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class DeleteTemplateRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }
    }

    public partial class DeleteTemplateResponse
    {
    }

    public partial class GetTemplateRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }
    }

    public partial class GetTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.GetTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class ListTemplatesRequest
    {
        [System.Text.Json.Serialization.JsonIgnore]
        public int? Page { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public string? Search { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public int? Size { get { throw null; } set { } }
    }

    public partial class ListTemplatesResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public System.Collections.Generic.IReadOnlyList<Shared.ListTemplatesResponseDataItem>? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("pageable")]
        public Shared.ListTemplatesResponsePageable? Pageable { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class PreviewTemplateRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("html_template")]
        public string? HtmlTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("stylesheet_id")]
        public int? StylesheetId { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("subject_template")]
        public required string SubjectTemplate { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_data")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? TemplateData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("text_template")]
        public string? TextTemplate { get { throw null; } set { } }
    }

    public partial class PreviewTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.PreviewTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class SendTestEmailRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("from")]
        public string? From { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("language")]
        public string? Language { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("template_data")]
        public System.Collections.Generic.IReadOnlyDictionary<string, System.Text.Json.JsonElement>? TemplateData { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("to")]
        public required System.Collections.Generic.IReadOnlyList<string> To { get { throw null; } set { } }
    }

    public partial class SendTestEmailResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.SendTestEmailResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }

    public partial class UpdateTemplateRequest
    {
        [System.Text.Json.Serialization.JsonPropertyName("default_language")]
        public string? DefaultLanguage { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("description")]
        public string? Description { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonIgnore]
        public required int Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public string? Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("sample_data")]
        public string? SampleData { get { throw null; } set { } }
    }

    public partial class UpdateTemplateResponse
    {
        [System.Text.Json.Serialization.JsonPropertyName("data")]
        public Shared.UpdateTemplateResponseData? Data { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("success")]
        public bool? Success { get { throw null; } set { } }
    }
}

namespace CommunityToolkit.Aspire.Posta.Transport
{
    public sealed partial class PostaApiException : System.Net.Http.HttpRequestException
    {
        public PostaApiException(System.Net.HttpStatusCode statusCode, string? responseBody, string message) { }

        public string? ResponseBody { get { throw null; } }
    }

    public sealed partial class PostaRequest
    {
        public string? BearerToken { get { throw null; } init { } }

        public object? Body { get { throw null; } init { } }

        public System.Net.Http.HttpContent? Content { get { throw null; } init { } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string> Headers { get { throw null; } init { } }

        public System.Collections.Generic.IReadOnlyDictionary<string, object?> PathParameters { get { throw null; } init { } }

        public System.Collections.Generic.IReadOnlyDictionary<string, object?> Query { get { throw null; } init { } }
    }

    public sealed partial class PostaStreamResponse : System.IDisposable, System.IAsyncDisposable
    {
        public PostaStreamResponse(System.Net.Http.HttpResponseMessage response, System.IO.Stream stream) { }

        public System.Net.Http.Headers.HttpContentHeaders Headers { get { throw null; } }

        public System.Net.HttpStatusCode StatusCode { get { throw null; } }

        public System.IO.Stream Stream { get { throw null; } }

        public void Dispose() { }

        public System.Threading.Tasks.ValueTask DisposeAsync() { throw null; }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspirePostaExtensions
    {
        public static void AddKeyedPostaClient(this IHostApplicationBuilder builder, object serviceKey, string connectionName, System.Action<CommunityToolkit.Aspire.Posta.Configuration.PostaClientSettings>? configureSettings = null, string? configurationSectionName = null) { }

        public static void AddKeyedPostaClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.Posta.Configuration.PostaClientSettings>? configureSettings = null, string? configurationSectionName = null) { }

        public static void AddPostaClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.Posta.Configuration.PostaClientSettings>? configureSettings = null, string? configurationSectionName = null) { }
    }
}