//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.RavenDB.Client
{
    public sealed partial class RavenDBClientSettings
    {
        public System.Security.Cryptography.X509Certificates.X509Certificate2? Certificate { get { throw null; } set { } }

        public string? CertificatePassword { get { throw null; } set { } }

        public string? CertificatePath { get { throw null; } set { } }

        public bool CreateDatabase { get { throw null; } set { } }

        public string? DatabaseName { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }

        public bool DisableTracing { get { throw null; } set { } }

        public int? HealthCheckTimeout { get { throw null; } set { } }

        public System.Action<Raven.Client.Documents.IDocumentStore>? ModifyDocumentStore { get { throw null; } set { } }

        public string[]? Urls { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class RavenDBClientExtension
    {
        public static void AddKeyedRavenDBClient(this IHostApplicationBuilder builder, object serviceKey, CommunityToolkit.Aspire.RavenDB.Client.RavenDBClientSettings settings) { }

        public static void AddKeyedRavenDBClient(this IHostApplicationBuilder builder, object serviceKey, string connectionName, System.Action<CommunityToolkit.Aspire.RavenDB.Client.RavenDBClientSettings>? configureSettings = null) { }

        public static void AddRavenDBClient(this IHostApplicationBuilder builder, CommunityToolkit.Aspire.RavenDB.Client.RavenDBClientSettings settings) { }

        public static void AddRavenDBClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.RavenDB.Client.RavenDBClientSettings>? configureSettings = null) { }
    }
}