//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class JavaAppHostingExtension
    {
        [System.Obsolete("Use AddJavaContainerApp instead. This method will be removed in a future version.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppContainerResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, ApplicationModel.JavaAppContainerResourceOptions options) { throw null; }

        [System.Obsolete("Use AddJavaApp(string, string, string, string[]?) instead. This method will be removed in a future version.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, string workingDirectory, ApplicationModel.JavaAppExecutableResourceOptions options) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, string workingDirectory, string jarPath, string[]? args = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> AddJavaApp(this IDistributedApplicationBuilder builder, string name, string workingDirectory) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppContainerResource> AddJavaContainerApp(this IDistributedApplicationBuilder builder, string name, string image, string? imageTag = null) { throw null; }

        [System.Obsolete("Use AddJavaContainerApp instead. This method will be removed in a future version.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppContainerResource> AddSpringApp(this IDistributedApplicationBuilder builder, string name, ApplicationModel.JavaAppContainerResourceOptions options) { throw null; }

        [System.Obsolete("Use AddJavaApp instead. This method will be removed in a future version.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> AddSpringApp(this IDistributedApplicationBuilder builder, string name, string workingDirectory, ApplicationModel.JavaAppExecutableResourceOptions options) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithGradleBuild(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, params string[] args) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithGradleTask(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, string task, params string[] args) { throw null; }

        public static ApplicationModel.IResourceBuilder<T> WithJvmArgs<T>(this ApplicationModel.IResourceBuilder<T> builder, string[] args)
            where T : ApplicationModel.IResourceWithEnvironment { throw null; }

        [System.Obsolete("Use WithMavenBuild(string?, params string[]) instead. This method will be removed in a future version.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithMavenBuild(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, MavenOptions mavenOptions) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithMavenBuild(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, params string[] args) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithMavenGoal(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, string goal, params string[] args) { throw null; }

        public static ApplicationModel.IResourceBuilder<T> WithOtelAgent<T>(this ApplicationModel.IResourceBuilder<T> builder, string? agentPath = null)
            where T : ApplicationModel.IResourceWithEnvironment { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> WithWrapperPath(this ApplicationModel.IResourceBuilder<ApplicationModel.JavaAppExecutableResource> builder, string wrapperScript) { throw null; }
    }

    [System.Obsolete("This class will be removed in a future version.")]
    public sealed partial class MavenOptions
    {
        public string[] Args { get { throw null; } set { } }

        public string Command { get { throw null; } set { } }

        public string? WorkingDirectory { get { throw null; } set { } }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class GradleBuildResource : ExecutableResource
    {
        public GradleBuildResource(string name, string wrapperScript, string workingDirectory) : base(default!, default!, default!) { }
    }

    public partial class JavaAppContainerResource : ContainerResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public JavaAppContainerResource(string name, string? entrypoint = null) : base(default!, default) { }
    }

    [System.Obsolete("This class will be removed in a future version.")]
    public partial class JavaAppContainerResourceOptions
    {
        public string[]? Args { get { throw null; } set { } }

        public string? ContainerImageName { get { throw null; } set { } }

        public string ContainerImageTag { get { throw null; } set { } }

        public string? ContainerRegistry { get { throw null; } set { } }

        public string? OtelAgentPath { get { throw null; } set { } }

        public int Port { get { throw null; } set { } }

        public int TargetPort { get { throw null; } set { } }
    }

    public partial class JavaAppExecutableResource : ExecutableResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource, IResourceWithWaitSupport
    {
        [System.Obsolete("Use JavaAppExecutableResource(string, string) instead. This constructor will be removed in a future version.")]
        public JavaAppExecutableResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }

        public JavaAppExecutableResource(string name, string workingDirectory) : base(default!, default!, default!) { }

        public string? JarPath { get { throw null; } set { } }
    }

    [System.Obsolete("This class will be removed in a future version.")]
    public partial class JavaAppExecutableResourceOptions
    {
        public string? ApplicationName { get { throw null; } set { } }

        public string[]? Args { get { throw null; } set { } }

        public string[]? JvmArgs { get { throw null; } set { } }

        public string? OtelAgentPath { get { throw null; } set { } }

        public int Port { get { throw null; } set { } }
    }

    public partial class MavenBuildResource : ExecutableResource
    {
        public MavenBuildResource(string name, string wrapperScript, string workingDirectory) : base(default!, default!, default!) { }
    }
}