//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class LogtoBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> AddLogto(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresServerResource> postgres, string databaseName = "logto_db", int? port = null, int? adminPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithAdminEndpoint(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, string url) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDatabase(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresServerResource> postgres, string databaseName = "logto_db") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDatabaseSeeding(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, string source) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDeprecationTracing(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builderWithResource) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithDisableAdminConsole(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, bool disable) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithNodeEnv(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, string env) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithRedis(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> redis) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithResourcePort(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, int? port = null, int? adminPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithSecretVault(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, string secretVaultKek) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithSensitiveUsername(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, bool sensitiveUsername) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> WithTrustProxyHeader(this ApplicationModel.IResourceBuilder<ApplicationModel.LogtoResource> builder, bool trustProxyHeader) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public sealed partial class LogtoResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public LogtoResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}