//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class JavaScriptHostingExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxAppResource> AddApp(this ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> builder, string name, string? appName = null, System.Func<ApplicationModel.IResourceBuilder<ApplicationModel.NxAppResource>, ApplicationModel.IResourceBuilder<ApplicationModel.NxAppResource>>? configure = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoAppResource> AddApp(this ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> builder, string name, string? filter = null, System.Func<ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoAppResource>, ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoAppResource>>? configure = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> AddNxApp(this IDistributedApplicationBuilder builder, string name, string? workingDirectory = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> AddTurborepoApp(this IDistributedApplicationBuilder builder, string name, string? workingDirectory = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithMappedEndpointPort<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string? endpointName = null)
            where TResource : JavaScript.JavaScriptAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> WithNpm(this ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> WithNpm(this ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> WithPackageManagerLaunch(this ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> builder, string? packageManager = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> WithPackageManagerLaunch(this ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> builder, string? packageManager = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> WithPnpm(this ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> WithPnpm(this ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> WithYarn(this ApplicationModel.IResourceBuilder<ApplicationModel.NxResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> WithYarn(this ApplicationModel.IResourceBuilder<ApplicationModel.TurborepoResource> builder, bool install = false, System.Action<ApplicationModel.IResourceBuilder<JavaScript.JavaScriptInstallerResource>>? configureInstaller = null) { throw null; }
    }

    public sealed partial class JavaScriptPackageManagerConfiguredAnnotation : ApplicationModel.IResourceAnnotation
    {
        public JavaScriptPackageManagerConfiguredAnnotation(string packageManager) { }

        public string PackageManager { get { throw null; } }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class NxAppResource : JavaScript.JavaScriptAppResource
    {
        public NxAppResource(string name, string workingDirectory, string appName, string command = "nx") : base(default!, default!, default!) { }

        public string AppName { get { throw null; } }
    }

    public partial class NxResource : Resource
    {
        public NxResource(string name, string workingDirectory) : base(default!) { }

        public string WorkingDirectory { get { throw null; } }
    }

    public partial class TurborepoAppResource : JavaScript.JavaScriptAppResource
    {
        public TurborepoAppResource(string name, string workingDirectory, string filter, string command = "turbo") : base(default!, default!, default!) { }

        public string Filter { get { throw null; } }
    }

    public partial class TurborepoResource : Resource
    {
        public TurborepoResource(string name, string workingDirectory) : base(default!) { }

        public string WorkingDirectory { get { throw null; } }
    }
}