@CommunityToolkit.Aspire.Hosting.ActiveMQ.MassTransit_HostAddress = http://localhost:5004

POST http://localhost:5004/send/Hello%20World
Accept: application/json

###
GET http://localhost:5004/alive
Accept: application/json

###
GET http://localhost:5004/received
Accept: application/json

### Jolokia call for Classic broker status
GET http://admin:admin@localhost:8161/api/jolokia/read/org.apache.activemq:type=Broker,brokerName=localhost,service=Health/CurrentStatus
origin: localhost

### Jolokia call for Artemis broker status
GET http://admin:admin@localhost:8161/console/jolokia/read/org.apache.activemq.artemis:broker=%220.0.0.0%22/Started
origin: localhost

