//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DenoAppHostingExtensions
    {
        [AspireExport("addDenoApp", Description = "Adds a Deno app resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DenoAppResource> AddDenoApp(this IDistributedApplicationBuilder builder, string name, string scriptPath, string? workingDirectory = null, string[]? permissionFlags = null, string[]? args = null) { throw null; }

        [AspireExport("addDenoTask", Description = "Adds a Deno task resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DenoAppResource> AddDenoTask(this IDistributedApplicationBuilder builder, string name, string? workingDirectory = null, string taskName = "start", string[]? args = null) { throw null; }

        [AspireExportIgnore(Reason = "Action<IResourceBuilder<DenoInstallerResource>> is not ATS-compatible. Use the overload without configureInstaller instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DenoAppResource> WithDenoPackageInstallation(this ApplicationModel.IResourceBuilder<ApplicationModel.DenoAppResource> resource, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DenoInstallerResource>>? configureInstaller = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class DenoAppResource : ExecutableResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public DenoAppResource(string name, string command, string workingDirectory) : base(default!, default!, default!) { }
    }

    public partial class DenoInstallerResource : ExecutableResource
    {
        public DenoInstallerResource(string name, string workingDirectory) : base(default!, default!, default!) { }
    }
}