<Project Sdk="Aspire.AppHost.Sdk/13.5.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>c25ab70b-35c0-4661-8ba7-554d7314f852</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.N8n\CommunityToolkit.Aspire.Hosting.N8n.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
