//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class UmamiBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.UmamiResource> AddUmami(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? secret = null, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.UmamiResource> WithPostgreSQL(this ApplicationModel.IResourceBuilder<ApplicationModel.UmamiResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresDatabaseResource> database) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class UmamiResource : ContainerResource
    {
        public UmamiResource(string name, ParameterResource secret) : base(default!, default) { }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ParameterResource SecretParameter { get { throw null; } }
    }
}