//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public enum KeyType
    {
        Ed25519 = 0,
        Rsa = 1
    }

    public static partial class SftpHostingExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> AddSftp(this IDistributedApplicationBuilder builder, string name, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> WithHostKeyFile(this ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> builder, string keyFile, KeyType keyType) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> WithUserKeyFile(this ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> builder, string username, string keyFile, KeyType keyType) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> WithUsersFile(this ApplicationModel.IResourceBuilder<ApplicationModel.SftpContainerResource> builder, string usersFile) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class SftpContainerResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public SftpContainerResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}