# Multi-resource example — API dependencies managed by Carton
# The worker uses cpanm + WithPackage() instead.

requires 'Log::Any';
requires 'Mojolicious';
requires 'Mojolicious::Lite';
requires 'Mojolicious::Plugin::OpenTelemetry';
requires 'Log::Any::Adapter::MojoLog';
requires 'OpenTelemetry::SDK';
requires 'Sentinel';
requires 'Object::Pad';
requires 'Syntax::Keyword::Dynamically';