//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.SeaweedFS.Client
{
    public sealed partial class SeaweedFSFilerClient
    {
        public SeaweedFSFilerClient(System.Net.Http.HttpClient httpClient) { }

        public System.Net.Http.HttpClient HttpClient { get { throw null; } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class SeaweedFSClientBuilderExtensionMethods
    {
        public static void AddSeaweedFSFilerClient(this IHostApplicationBuilder builder, string connectionName, System.Action<SeaweedFSClientSettings>? configureSettings = null, string? configurationSectionName = null) { }

        public static void AddSeaweedFSS3Client(this IHostApplicationBuilder builder, string connectionName, System.Action<SeaweedFSClientSettings>? configureSettings = null, string? configurationSectionName = null) { }
    }

    public sealed partial class SeaweedFSClientSettings
    {
        public string? AccessKey { get { throw null; } set { } }

        public System.Action<Amazon.S3.AmazonS3Config>? ConfigureS3Config { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }

        public System.Uri? Endpoint { get { throw null; } set { } }

        public System.Uri? FilerEndpoint { get { throw null; } set { } }

        public bool ForcePathStyle { get { throw null; } set { } }

        public string? SecretKey { get { throw null; } set { } }

        public bool UseSsl { get { throw null; } set { } }
    }
}