//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class UvAppHostingExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.UvAppResource> AddUvApp(this IDistributedApplicationBuilder builder, string name, string projectDirectory, string scriptPath, params string[] scriptArgs) { throw null; }
    }

    public static partial class UvicornAppHostingExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.UvicornAppResource> AddUvicornApp(this IDistributedApplicationBuilder builder, string name, string projectDirectory, string appName, params string[] args) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class UvAppResource : Python.PythonAppResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public UvAppResource(string name, string executablePath, string workingDirectory) : base(default!, default!, default!) { }
    }

    public partial class UvicornAppResource : Python.PythonAppResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public UvicornAppResource(string name, string executablePath, string workingDirectory) : base(default!, default!, default!) { }
    }
}