//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class StreamlitAppHostingExtension
    {
        [System.Diagnostics.CodeAnalysis.Experimental("CTASPIRE001", UrlFormat = "https://github.com/CommunityToolkit/Aspire/issues/{0}")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StreamlitAppResource> AddStreamlitApp(this IDistributedApplicationBuilder builder, string name, string appDirectory, string scriptPath) { throw null; }
    }

    public static partial class UvAppHostingExtension
    {
        [System.Obsolete("AddUvApp is now part of Aspire.Hosting.Python. Use Aspire.Hosting.Python.PythonAppResourceBuilderExtensions.AddPythonApp with WithUvEnvironment instead. This method will be removed in a future release.")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.UvAppResource> AddUvApp(this IDistributedApplicationBuilder builder, string name, string projectDirectory, string scriptPath, params string[] scriptArgs) { throw null; }
    }

    public static partial class UvicornAppHostingExtension
    {
        [System.Obsolete("AddUvicornApp is now part of Aspire.Hosting.Python. Use the Aspire.Hosting.Python.PythonAppResourceBuilderExtensions.AddUvicornApp method instead. This method will be removed in a future release.")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.UvicornAppResource> AddUvicornApp(this IDistributedApplicationBuilder builder, string name, string projectDirectory, string appName, params string[] args) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class StreamlitAppResource : Python.PythonAppResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public StreamlitAppResource(string name, string executablePath, string workingDirectory) : base(default!, default!, default!) { }
    }

    [System.Obsolete("UvAppResource is now superseded by functionality in Aspire.Hosting.Python. Use Aspire.Hosting.Python.PythonAppResourceBuilderExtensions.AddPythonApp with WithUvEnvironment instead. This class will be removed in a future release.")]
    public partial class UvAppResource : Python.PythonAppResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public UvAppResource(string name, string executablePath, string workingDirectory) : base(default!, default!, default!) { }
    }

    [System.Obsolete("UvicornAppResource is now part of Aspire.Hosting.Python. Use Aspire.Hosting.ApplicationModel.UvicornAppResource instead. This class will be removed in a future release.")]
    public partial class UvicornAppResource : Python.PythonAppResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public UvicornAppResource(string name, string executablePath, string workingDirectory) : base(default!, default!, default!) { }
    }
}