//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class KindClusterBuilderExtensions
    {
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> AddKindCluster(this Aspire.Hosting.IDistributedApplicationBuilder builder, string name, string? clusterName = null, string? kubeconfigPath = null) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithConfig(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, string configPath) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithHelmChart(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, string releaseName, string chart, string @namespace = "default", string? valuesFile = null) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithKubernetesVersion(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, string? kubernetesVersion) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithManifest(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, string manifestPath) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithNodeCount(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, int nodeCount) { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithPortMapping(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, int hostPort, int containerPort, string protocol = "TCP") { throw null; }
        public static Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> WithWaitForReady(this Aspire.Hosting.ApplicationModel.IResourceBuilder<Aspire.Hosting.ApplicationModel.KindClusterResource> builder, System.TimeSpan timeout) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial class KindClusterResource : Aspire.Hosting.ApplicationModel.Resource, Aspire.Hosting.ApplicationModel.IResourceWithConnectionString
    {
        public KindClusterResource(string name, string clusterName, string kubeconfigPath) : base(default!) { }
        public string ClusterName { get { throw null; } }
        public string? ConfigPath { get { throw null; } set { } }
        public System.Collections.Generic.IReadOnlyList<KindHelmChart> HelmCharts { get { throw null; } }
        public string KubeconfigPath { get { throw null; } }
        public string? KubernetesVersion { get { throw null; } set { } }
        public System.Collections.Generic.IReadOnlyList<string> ManifestPaths { get { throw null; } }
        public int NodeCount { get { throw null; } set { } }
        public System.Collections.Generic.IReadOnlyList<KindPortMapping> PortMappings { get { throw null; } }
        public System.TimeSpan ReadyTimeout { get { throw null; } set { } }
        public Aspire.Hosting.ApplicationModel.ReferenceExpression ConnectionStringExpression { get { throw null; } }
    }

    public partial record KindHelmChart(string ReleaseName, string Chart, string Namespace = "default", string? ValuesFile = null);

    public partial record struct KindPortMapping(int HostPort, int ContainerPort, string Protocol = "TCP");
}
