//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public enum ClusterLifetime
    {
        Session = 0,
        Persistent = 1
    }

    public static partial class KindClusterResourceBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> AddKindCluster(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithClusterLifetime<T>(this ApplicationModel.IResourceBuilder<T> builder, ClusterLifetime lifetime)
            where T : ApplicationModel.IKindResource { throw null; }

        [AspireExportIgnore(Reason = "Action<KindConfigModel> is not ATS-compatible. Configure Kind config through ATS-supported APIs.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> WithKindConfig(this ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> builder, System.Action<ApplicationModel.KindConfigModel> configure) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithKubernetesVersion<T>(this ApplicationModel.IResourceBuilder<T> builder, string version)
            where T : ApplicationModel.IKindResource { throw null; }

        [AspireExport("withKindClusterReference")]
        public static ApplicationModel.IResourceBuilder<T> WithReference<T>(this ApplicationModel.IResourceBuilder<T> builder, ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> kind)
            where T : ApplicationModel.IResourceWithEnvironment { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithWorkerNodes<T>(this ApplicationModel.IResourceBuilder<T> builder, int count)
            where T : ApplicationModel.IKindResource { throw null; }
    }

    public static partial class KindContainerExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ContainerResource> WithKindNetwork(this ApplicationModel.IResourceBuilder<ApplicationModel.ContainerResource> builder) { throw null; }

        [AspireExport("withKindContainerReference")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.ContainerResource> WithReference(this ApplicationModel.IResourceBuilder<ApplicationModel.ContainerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> kind) { throw null; }
    }

    public static partial class KindHelmChartResourceBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> AddHelmChart(this ApplicationModel.IResourceBuilder<ApplicationModel.KindClusterResource> builder, string name, string chartRef) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> WithChartVersion(this ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> builder, string version) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> WithHelmValue(this ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> builder, string key, string value) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> WithHelmValuesFile(this ApplicationModel.IResourceBuilder<ApplicationModel.KindHelmChartResource> builder, string path) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<T> WithNamespace<T>(this ApplicationModel.IResourceBuilder<T> builder, string @namespace)
            where T : ApplicationModel.KindDeployedResource { throw null; }
    }

    public static partial class KubernetesEnvironmentKindExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KindEnvironmentResource> WithKind(this ApplicationModel.IResourceBuilder<Kubernetes.KubernetesEnvironmentResource> builder) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial interface IKindResource : IResource
    {
        string KubeconfigPath { get; }
    }

    public sealed partial class KindClusterResource : Resource, IKindResource, IResource, IResourceWithWaitSupport
    {
        public KindClusterResource(string name) : base(default!) { }

        public string ContainerKubeconfigPath { get { throw null; } }

        public string KubeconfigPath { get { throw null; } }
    }

    public sealed partial class KindConfigModel
    {
        public string ApiVersion { get { throw null; } set { } }

        public System.Collections.Generic.IList<string>? ContainerdConfigPatches { get { throw null; } set { } }

        public System.Collections.Generic.IDictionary<string, bool>? FeatureGates { get { throw null; } set { } }

        public string Kind { get { throw null; } set { } }

        public System.Collections.Generic.IList<string>? KubeadmConfigPatches { get { throw null; } set { } }

        public KindNetworkingModel? Networking { get { throw null; } set { } }

        public System.Collections.Generic.IList<KindNodeModel> Nodes { get { throw null; } }

        public System.Collections.Generic.IDictionary<string, string>? RuntimeConfig { get { throw null; } set { } }
    }

    public abstract partial class KindDeployedResource : Resource, IResourceWithParent<KindClusterResource>, IResourceWithParent, IResource, IResourceWithWaitSupport
    {
        protected KindDeployedResource(string name, KindClusterResource parent) : base(default!) { }

        public string? Namespace { get { throw null; } set { } }

        public KindClusterResource Parent { get { throw null; } }
    }

    public sealed partial class KindEnvironmentResource : Resource, IKindResource, IResource, IResourceWithParent<Kubernetes.KubernetesEnvironmentResource>, IResourceWithParent
    {
        public KindEnvironmentResource(string name, Kubernetes.KubernetesEnvironmentResource parent) : base(default!) { }

        public string KubeconfigPath { get { throw null; } }

        public Kubernetes.KubernetesEnvironmentResource Parent { get { throw null; } }
    }

    public partial class KindHelmChartResource : KindDeployedResource
    {
        public KindHelmChartResource(string name, string chartRef, KindClusterResource parent) : base(default!, default!) { }

        public string ChartRef { get { throw null; } }

        public string ReleaseName { get { throw null; } }

        public System.Collections.Generic.Dictionary<string, string> Values { get { throw null; } }

        public System.Collections.Generic.List<string> ValuesFiles { get { throw null; } }

        public string? Version { get { throw null; } set { } }
    }

    public sealed partial class KindMountModel
    {
        public string? ContainerPath { get { throw null; } set { } }

        public string? HostPath { get { throw null; } set { } }

        public string? Propagation { get { throw null; } set { } }

        public bool? ReadOnly { get { throw null; } set { } }

        public bool? SelinuxRelabel { get { throw null; } set { } }
    }

    public sealed partial class KindNetworkingModel
    {
        public string? ApiServerAddress { get { throw null; } set { } }

        public int? ApiServerPort { get { throw null; } set { } }

        public bool? DisableDefaultCNI { get { throw null; } set { } }

        public string? IpFamily { get { throw null; } set { } }

        public string? KubeProxyMode { get { throw null; } set { } }

        public string? PodSubnet { get { throw null; } set { } }

        public string? ServiceSubnet { get { throw null; } set { } }
    }

    public sealed partial class KindNodeModel
    {
        public System.Collections.Generic.IList<KindMountModel>? ExtraMounts { get { throw null; } set { } }

        public System.Collections.Generic.IList<KindPortMappingModel>? ExtraPortMappings { get { throw null; } set { } }

        public string? Image { get { throw null; } set { } }

        public System.Collections.Generic.IList<string>? KubeadmConfigPatches { get { throw null; } set { } }

        public System.Collections.Generic.IDictionary<string, string>? Labels { get { throw null; } set { } }

        public string Role { get { throw null; } set { } }
    }

    public sealed partial class KindPortMappingModel
    {
        public int? ContainerPort { get { throw null; } set { } }

        public int? HostPort { get { throw null; } set { } }

        public string? ListenAddress { get { throw null; } set { } }

        public string? Protocol { get { throw null; } set { } }
    }
}