//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.EventStore
{
    public sealed partial class EventStoreSettings
    {
        public string? ConnectionString { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }

        public bool DisableTracing { get { throw null; } set { } }

        public System.TimeSpan? HealthCheckTimeout { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireEventStoreExtensions
    {
        public static void AddEventStoreClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.EventStore.EventStoreSettings>? configureSettings = null) { }

        public static void AddKeyedEventStoreClient(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.EventStore.EventStoreSettings>? configureSettings = null) { }
    }
}