GET http://localhost:55035/ping

###

GET http://localhost:55035/user/foo

###

POST http://localhost:55035/admin
Content-Type: application/json
Authorization: Basic Zm9vOmJhcg==

{
    "value": "bar"
}