GET http://localhost:59542/ping

###

GET http://localhost:59542/user/foo

###

POST http://localhost:59542/admin
Content-Type: application/json
Authorization: Basic Zm9vOmJhcg==

{
    "value": "bar"
}