//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    [System.Obsolete("EventStore has been rebranded to KurrentDB. Use CommunityToolkit.Aspire.Hosting.KurrentDB and KurrentDBBuilderExtensions instead. This integration will be removed in a future release.")]
    public static partial class EventStoreBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.EventStoreResource> AddEventStore(this IDistributedApplicationBuilder builder, string name, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.EventStoreResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.EventStoreResource> builder, string source) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.EventStoreResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.EventStoreResource> builder, string? name = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [System.Obsolete("EventStore has been rebranded to KurrentDB. Use CommunityToolkit.Aspire.Hosting.KurrentDB and KurrentDBResource instead. This integration will be removed in a future release.")]
    public partial class EventStoreResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public EventStoreResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}