//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.Bitwarden.SecretManager
{
    public sealed partial class BitwardenSecretManagerClientSettings
    {
        public string AccessToken { get { throw null; } set { } }

        public string ApiUrl { get { throw null; } set { } }

        public string? AuthCacheDirectory { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }

        public System.TimeSpan? HealthCheckTimeout { get { throw null; } set { } }

        public string IdentityUrl { get { throw null; } set { } }

        public System.Guid OrganizationId { get { throw null; } set { } }

        public System.Guid ProjectId { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireBitwardenSecretManagerExtensions
    {
        public static void AddBitwardenSecretManagerClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.Bitwarden.SecretManager.BitwardenSecretManagerClientSettings>? configureSettings = null) { }

        public static void AddKeyedBitwardenSecretManagerClient(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.Bitwarden.SecretManager.BitwardenSecretManagerClientSettings>? configureSettings = null) { }
    }
}