//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DataApiBuilderHostingExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DataApiBuilderContainerResource> AddDataAPIBuilder(this IDistributedApplicationBuilder builder, string name, int? httpPort = null, params string[] configFilePaths) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.DataApiBuilderContainerResource> AddDataAPIBuilder(this IDistributedApplicationBuilder builder, string name, params string[] configFilePaths) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class DataApiBuilderContainerResource : ContainerResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public DataApiBuilderContainerResource(string name, string? entrypoint = null) : base(default!, default) { }
    }
}