//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class MailPitHostingExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.MailPitContainerResource> AddMailPit(this IDistributedApplicationBuilder builder, string name, int? httpPort = null, int? smtpPort = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.MailPitContainerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.MailPitContainerResource> builder, string source, bool isReadOnly = false) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.MailPitContainerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.MailPitContainerResource> builder, string name, bool isReadOnly = false) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class MailPitContainerResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public MailPitContainerResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }
    }
}