//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.Logto.Client
{
    public static partial class LogtoConnectionStringHelper
    {
        public static string? GetEndpointFromConnectionString(string? connectionString) { throw null; }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class LogtoClientBuilder
    {
        public static AspNetCore.Authentication.AuthenticationBuilder AddLogtoJwtBearer(this AspNetCore.Authentication.AuthenticationBuilder builder, string serviceName, System.Collections.Generic.IEnumerable<string> appIdentification, string authenticationScheme = "Bearer", string? configurationSectionName = "Aspire:Logto:Client", System.Action<AspNetCore.Authentication.JwtBearer.JwtBearerOptions>? configureOptions = null) { throw null; }

        public static AspNetCore.Authentication.AuthenticationBuilder AddLogtoJwtBearer(this AspNetCore.Authentication.AuthenticationBuilder builder, string serviceName, string appIdentification, string authenticationScheme = "Bearer", string? configurationSectionName = "Aspire:Logto:Client", System.Action<AspNetCore.Authentication.JwtBearer.JwtBearerOptions>? configureOptions = null) { throw null; }

        public static DependencyInjection.IServiceCollection AddLogtoOIDC(this IHostApplicationBuilder builder, string? connectionName = null, string? configurationSectionName = "Aspire:Logto:Client", string authenticationScheme = "Logto", string cookieScheme = "Logto.Cookie", System.Action<Logto.AspNetCore.Authentication.LogtoOptions>? logtoOptions = null, System.Action<AspNetCore.Authentication.OpenIdConnect.OpenIdConnectOptions>? oidcOptions = null) { throw null; }
    }
}