//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.MassTransit.RabbitMQ
{
    public sealed partial class MassTransitRabbitMqSettings
    {
        public bool DisableTelemetry { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class MassTransitRabbitMqExtensions
    {
        public static void AddMassTransitRabbitMq(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.MassTransit.RabbitMQ.MassTransitRabbitMqSettings>? configureOptions = null, System.Action<MassTransit.IBusRegistrationConfigurator>? massTransitConfiguration = null) { }

        public static void AddMassTransitRabbitMq<TBus>(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.MassTransit.RabbitMQ.MassTransitRabbitMqSettings>? configureOptions = null, System.Action<MassTransit.IBusRegistrationConfigurator>? massTransitConfiguration = null)
            where TBus : class, MassTransit.IBus { }
    }
}