//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DistributedApplicationBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlywayResource> AddFlyway(this IDistributedApplicationBuilder builder, string name, string migrationScriptsPath) { throw null; }

        public sealed partial class <G>$2768207B2D58D0758B760BF9865B3152
        {
            internal <G>$2768207B2D58D0758B760BF9865B3152() { }

            [System.Runtime.CompilerServices.ExtensionMarker("<M>$7E82668A53676F97137EF4F844E46C25")]
            public ApplicationModel.IResourceBuilder<ApplicationModel.FlywayResource> AddFlyway(string name, string migrationScriptsPath) { throw null; }

            public static partial class <M>$7E82668A53676F97137EF4F844E46C25
            {
                [System.Runtime.CompilerServices.CompilerGenerated]
                public static void <Extension>$(IDistributedApplicationBuilder builder) { }
            }
        }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial class FlywayResource : ContainerResource
    {
        public FlywayResource(string name) : base(default!, default) { }
    }

    public sealed partial record FlywayResourceConfiguration()
    {
        public required string MigrationScriptsPath { get { throw null; } init { } }
    }
}

namespace CommunityToolkit.Aspire.Hosting.Flyway
{
    public static partial class FlywayResourceBuilderExtensions
    {
        public static global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.FlywayResource> WithTelemetryOptIn(this global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.FlywayResource> builder) { throw null; }

        public sealed partial class <G>$3630027837079DBDB4C7B2F0326D1811
        {
            internal <G>$3630027837079DBDB4C7B2F0326D1811() { }

            [System.Runtime.CompilerServices.ExtensionMarker("<M>$3C0C55E6ADDC766E6566DD2928E738EF")]
            public global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.FlywayResource> WithTelemetryOptIn() { throw null; }

            public static partial class <M>$3C0C55E6ADDC766E6566DD2928E738EF
            {
                [System.Runtime.CompilerServices.CompilerGenerated]
                public static void <Extension>$(global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.FlywayResource> builder) { }
            }
        }
    }
}