//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureContainerAppEnvironmentResourceBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<Azure.AppContainers.AzureContainerAppEnvironmentResource> WithDaprComponents(this ApplicationModel.IResourceBuilder<Azure.AppContainers.AzureContainerAppEnvironmentResource> builder) { throw null; }
    }

    public static partial class AzureDaprHostingExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.AzureDaprComponentResource> AddAzureDaprResource(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Dapr.IDaprComponentResource> builder, string name, System.Action<Azure.AzureResourceInfrastructure> configureInfrastructure) { throw null; }

        public static void AddScopes(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Dapr.IDaprComponentResource> builder, global::Azure.Provisioning.AppContainers.ContainerAppManagedEnvironmentDaprComponent daprComponent) { }

        public static global::Azure.Provisioning.AppContainers.ContainerAppManagedEnvironmentDaprComponent CreateDaprComponent(string bicepIdentifier, global::Azure.Provisioning.BicepValue<string> name, string componentType, string version) { throw null; }
    }

    public static partial class AzureKeyVaultDaprHostingExtensions
    {
        public static ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Dapr.IDaprComponentResource> ConfigureKeyVaultSecretsComponent(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Dapr.IDaprComponentResource> builder, global::Azure.Provisioning.ProvisioningParameter kvNameParam) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class AzureDaprComponentResource : Azure.AzureProvisioningResource
    {
        public AzureDaprComponentResource(string bicepIdentifier, System.Action<Azure.AzureResourceInfrastructure> configureInfrastructure) : base(default!, default!) { }
    }
}

namespace CommunityToolkit.Aspire.Hosting.Azure.Dapr
{
    public partial record AzureDaprComponentPublishingAnnotation(System.Action<global::Aspire.Hosting.Azure.AzureResourceInfrastructure> PublishingAction) : global::Aspire.Hosting.ApplicationModel.IResourceAnnotation
    {
    }
}