<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <ProjectReference Include="..\..\examples\n8n\CommunityToolkit.Aspire.Hosting.N8n.AppHost\CommunityToolkit.Aspire.Hosting.N8n.AppHost.csproj" />
    <ProjectReference Include="..\..\src\CommunityToolkit.Aspire.Hosting.N8n\CommunityToolkit.Aspire.Hosting.N8n.csproj" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Testing\CommunityToolkit.Aspire.Testing.csproj" />
  </ItemGroup>

</Project>
