//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.Minio.Client
{
    public partial class HeaderAppInformation
    {
        public string AppName { get { throw null; } set { } }

        public string AppVersion { get { throw null; } set { } }
    }

    public sealed partial class MinioClientSettings
    {
        public Microsoft.Extensions.DependencyInjection.ServiceLifetime ServiceLifetime;
        public MinioCredentials? Credentials { get { throw null; } set { } }

        public System.Uri? Endpoint { get { throw null; } set { } }

        public bool SetTraceOn { get { throw null; } set { } }

        public HeaderAppInformation? UserAgentHeaderInfo { get { throw null; } set { } }

        public bool UseSsl { get { throw null; } set { } }
    }

    public partial class MinioCredentials
    {
        public string AccessKey { get { throw null; } set { } }

        public string SecretKey { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class MinioClientBuilderExtensionMethods
    {
        public static void AddMinioClient(this IHostApplicationBuilder builder, string? connectionName = null, string? configurationSectionName = "Aspire:Minio:Client", System.Action<CommunityToolkit.Aspire.Minio.Client.MinioClientSettings>? configureSettings = null) { }
    }
}