//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SolrBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> AddSolr(this IDistributedApplicationBuilder builder, string name, int? port = null, string? coreName = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> WithConfigset(this ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> builder, string configSetName, string configSetPath) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> builder, string source, bool isReadOnly = false) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> builder, string? name = null, bool isReadOnly = false) { throw null; }
    }

    public sealed partial class SolrConfigSetAnnotation : ApplicationModel.IResourceAnnotation
    {
        public SolrConfigSetAnnotation(string configSetName, string configSetPath) { }

        public string ConfigSetName { get { throw null; } }

        public string ConfigSetPath { get { throw null; } }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class SolrResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public SolrResource(string name, string coreName) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string CoreName { get { throw null; } set { } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}