//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SolrBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SolrResource> AddSolr(this IDistributedApplicationBuilder builder, string name, int? port = null, string? coreName = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class SolrResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public SolrResource(string name, string coreName) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string CoreName { get { throw null; } set { } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}