//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SquadBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SquadResource> AddSquad(this IDistributedApplicationBuilder builder, string name, string? teamRoot = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial class SquadResource : Resource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public SquadResource(string name, string teamRoot) : base(default!) { }

        public System.Collections.Generic.IReadOnlyList<string> Agents { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string TeamRoot { get { throw null; } }
    }

    public sealed partial class SquadTeamAnnotation : IResourceAnnotation
    {
        public SquadTeamAnnotation(string teamRoot, string decisionsMdPath, string inboxDir, string agentRosterFile) { }

        public string AgentRosterFile { get { throw null; } }

        public string DecisionsMdPath { get { throw null; } }

        public string InboxDir { get { throw null; } }

        public string TeamRoot { get { throw null; } }
    }
}