//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RedisBuilderExtensions
    {
        [AspireExport(RunSyncOnBackgroundThread = true)]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> WithDbGate(this ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> builder, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DbGateContainerResource>>? configureContainer = null, string? containerName = null) { throw null; }

        [AspireExportIgnore(Reason = "Action<IResourceBuilder<DbxContainerResource>> is not supported reliably in polyglot app hosts. Use the container options overload instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> WithDbx(this ApplicationModel.IResourceBuilder<ApplicationModel.RedisResource> builder, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DbxContainerResource>>? configureContainer = null, string? containerName = null) { throw null; }
    }
}