//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SeaweedFSBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> AddSeaweedFS(this IDistributedApplicationBuilder builder, string name) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithAccessKey(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> accessKey) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, string source, bool isReadOnly = false) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, string? name = null, bool isReadOnly = false) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithFiler(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, int? filerPort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithHostPort(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, int? port) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithS3(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, int? s3Port = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithS3ConfigFile(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, string configFilePath) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> WithSecretKey(this ApplicationModel.IResourceBuilder<SeaweedFSContainerResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> secretKey) { throw null; }
    }

    public sealed partial class SeaweedFSContainerResource : ApplicationModel.ContainerResource, ApplicationModel.IResourceWithConnectionString, ApplicationModel.IResource, ApplicationModel.IExpressionValue, ApplicationModel.IValueProvider, ApplicationModel.IManifestExpressionProvider, ApplicationModel.IValueWithReferences
    {
        public SeaweedFSContainerResource(string name, ApplicationModel.ParameterResource accessKey, ApplicationModel.ParameterResource secretKey) : base(default!, default) { }

        public ApplicationModel.ParameterResource AccessKey { get { throw null; } }

        public ApplicationModel.ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public ApplicationModel.EndpointReference FilerEndpoint { get { throw null; } }

        public ApplicationModel.EndpointReference MasterEndpoint { get { throw null; } }

        public ApplicationModel.EndpointReference PrimaryEndpoint { get { throw null; } }

        public ApplicationModel.ParameterResource SecretKey { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ApplicationModel.ReferenceExpression>> ApplicationModel.IResourceWithConnectionString.GetConnectionProperties() { throw null; }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }
}