//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class RustFsBuilderExtensions
    {
        [AspireExport("addBuckets")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> AddBucket(this ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> builder, System.Collections.Generic.IReadOnlyList<string> bucketNames) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsBucketResource> AddBucket(this ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> builder, string bucketName) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> AddRustFs(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? accessKey = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? secretKey = null, int? port = null, int? consolePort = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> builder, string source) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> builder, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> WithSigningRegion(this ApplicationModel.IResourceBuilder<ApplicationModel.RustFsResource> builder, string region) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial class RustFsBucketResource : Resource, IResourceWithParent<RustFsResource>, IResourceWithParent, IResource, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public RustFsBucketResource(string name, string bucketName, RustFsResource parent) : base(default!) { }

        public string BucketName { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public RustFsResource Parent { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }

    public sealed partial class RustFsResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public RustFsResource(string name, ParameterResource accessKey, ParameterResource secretKey) : base(default!, default) { }

        public ParameterResource AccessKey { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ParameterResource SecretKey { get { throw null; } }

        public string SigningRegion { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }
}