#!/usr/bin/env python3
"""Generate the integrations table in README.md from src package projects."""

from __future__ import annotations

import argparse
import difflib
import re
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path

TABLE_START = "<!-- BEGIN AUTOGENERATED INTEGRATIONS TABLE -->"
TABLE_END = "<!-- END AUTOGENERATED INTEGRATIONS TABLE -->"


@dataclass(frozen=True)
class Integration:
    package_id: str
    short_name: str
    description: str
    readme_path: str
    deprecated: bool


def _find_repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _read_property(project: ET.ElementTree, name: str) -> str | None:
    for element in project.iter():
        if element.tag.endswith(name):
            value = (element.text or "").strip()
            if value:
                return value
    return None


def _load_integrations(repo_root: Path) -> list[Integration]:
    integrations: list[Integration] = []

    for project_path in sorted(repo_root.glob("src/**/CommunityToolkit.Aspire*.csproj")):
        tree = ET.parse(project_path)
        project = tree.getroot()

        package_id = _read_property(tree, "PackageId") or project_path.stem
        description = _read_property(tree, "Description")
        if description is None:
            continue

        readme = project_path.parent / "README.md"
        readme_rel = readme.relative_to(repo_root).as_posix() if readme.exists() else ""

        deprecated = False
        if readme.exists():
            readme_text = readme.read_text(encoding="utf-8", errors="ignore")
            deprecated = bool(re.search(r"\bthis integration is deprecated\b", readme_text, re.IGNORECASE))

        if "|" in description:
            description = description.replace("|", "\\|")

        if deprecated:
            description = f"⚠️ **Deprecated** — {description}"

        short_name = package_id.removeprefix("CommunityToolkit.Aspire.")

        integrations.append(
            Integration(
                package_id=package_id,
                short_name=short_name,
                description=description,
                readme_path=readme_rel,
                deprecated=deprecated,
            )
        )

    integrations.sort(key=lambda item: item.package_id.lower())
    return integrations


def _render_table(integrations: list[Integration]) -> str:
    lines: list[str] = [
        "| Package | Description |",
        "| --- | --- |",
    ]

    for integration in integrations:
        docs_link = integration.readme_path or "#"
        package = integration.package_id
        cell = (
            f"- **Learn More**: [`{integration.short_name}`]({docs_link}) <br /> "
            f"- Stable 📦: [![{package}](https://img.shields.io/nuget/v/{package})](https://nuget.org/packages/{package}/) <br /> "
            f"- Preview 📦: [![{package}](https://img.shields.io/nuget/vpre/{package}?label=nuget%20(preview))](https://nuget.org/packages/{package}/absoluteLatest)"
        )
        lines.append(f"| {cell} | {integration.description} |")

    return "\n".join(lines)


def _update_readme(content: str, table: str) -> str:
    block = f"{TABLE_START}\n{table}\n{TABLE_END}"

    if TABLE_START in content and TABLE_END in content:
        pattern = re.compile(rf"{re.escape(TABLE_START)}.*?{re.escape(TABLE_END)}", re.DOTALL)
        return pattern.sub(block, content, count=1)

    table_start = content.find("| Package")
    section_start = content.find("\n## 🙌 Getting Started")
    if table_start == -1 or section_start == -1 or section_start <= table_start:
        raise RuntimeError("Unable to locate integrations table section in README.md")

    return content[:table_start] + block + "\n" + content[section_start:]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Check if README integrations table is up to date")
    args = parser.parse_args()

    repo_root = _find_repo_root()
    readme_path = repo_root / "README.md"

    integrations = _load_integrations(repo_root)
    table = _render_table(integrations)

    existing = readme_path.read_text(encoding="utf-8")
    updated = _update_readme(existing, table)

    if args.check:
        if existing != updated:
            diff = "".join(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    updated.splitlines(keepends=True),
                    fromfile="README.md",
                    tofile="README.md (generated)",
                )
            )
            print("README integrations table is out of date.")
            print("Run: python eng/scripts/generate-readme-integrations.py")
            print(diff)
            return 1

        print("README integrations table is up to date.")
        return 0

    if existing != updated:
        readme_path.write_text(updated, encoding="utf-8")
        print("Updated README integrations table.")
    else:
        print("README integrations table already up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
