<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>7c142ab5-bd26-47c9-a173-6368e2e9df96</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.Mosquitto\CommunityToolkit.Aspire.Hosting.Mosquitto.csproj" IsAspireProjectResource="false" />
  </ItemGroup>

</Project>
