<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Chroma\CommunityToolkit.Aspire.Chroma.csproj" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Hosting.Chroma.ServiceDefaults\CommunityToolkit.Aspire.Hosting.Chroma.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
