<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>An Aspire hosting integration for n8n, a fair-code licensed workflow automation tool that combines AI capabilities with business process automation.</Description>
    <AdditionalPackageTags>n8n workload automation</AdditionalPackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting" />
    <PackageReference Include="BCrypt.Net-Next" />
  </ItemGroup>

</Project>
