//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class ZitadelHostingExtensions
    {
        [AspireExport("addZitadel", Description = "Adds a Zitadel container resource")]
        public static ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> AddZitadel(this IDistributedApplicationBuilder builder, string name, int? port = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? username = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? password = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? masterKey = null) { throw null; }

        [AspireExport("withExistingDatabase", Description = "Adds database support to the Zitadel resource using an existing PostgreSQL database")]
        public static ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> WithDatabase(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresDatabaseResource> database) { throw null; }

        [AspireExport("withDatabase", Description = "Adds database support to the Zitadel resource using a PostgreSQL server")]
        public static ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> WithDatabase(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresServerResource> server, string? databaseName = null) { throw null; }

        [AspireExport("withExternalDomain", Description = "Configures the external domain for the Zitadel resource")]
        public static ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> WithExternalDomain(this ApplicationModel.IResourceBuilder<CommunityToolkit.Aspire.Hosting.Zitadel.ZitadelResource> builder, string externalDomain) { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.Zitadel
{
    public sealed partial class ZitadelResource : global::Aspire.Hosting.ApplicationModel.ContainerResource
    {
        public ZitadelResource(string name) : base(default!, default) { }

        public required global::Aspire.Hosting.ApplicationModel.ParameterResource AdminPasswordParameter { get { throw null; } set { } }

        public required global::Aspire.Hosting.ApplicationModel.ParameterResource AdminUsernameParameter { get { throw null; } set { } }
    }
}