name: "Setup Runtimes, Caching, and Tools"
description: "Setup various runtimes, cache dependencies, and initialize tools"
inputs:
  name:
    description: "The name of the project or environment to configure"
    required: true
  docker-username:
    description: "The Docker username"
    required: true
  docker-password:
    description: "The Docker password"
    required: true
  docker-registry:
    description: "The Docker registry"
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Uvicorn
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uvicorn

    - uses: astral-sh/setup-uv@v5
      name: Install uv
      with:
        enable-cache: false

    - uses: actions/setup-go@v6
      name: Set up Go
      with:
        go-version: "^1.25.4"
        cache-dependency-path: |
          ./examples/golang/gin-api/go.sum

    - uses: actions/setup-java@v4
      name: Set up Java
      with:
        distribution: "microsoft"
        java-version: "21"

    - uses: actions/setup-node@v4
      name: Set up Node.js
      with:
        node-version: "latest"

    - uses: denoland/setup-deno@v2
      name: Setup Deno
      with:
        deno-version: v2.5.4

    - uses: oven-sh/setup-bun@v2
      name: Setup Bun
      with:
        bun-version: latest

    - uses: actions/cache@v4
      name: Cache NuGet packages
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
          ${{ runner.os }}-nuget-

    - uses: Swatinem/rust-cache@v2
      name: Cache Rust packages
      with:
        workspaces: "examples/rust/actix_api -> target"

    - name: Setup .NET dev certs
      shell: bash
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        dotnet dev-certs https

    - name: Setup Node globals
      shell: bash
      if: ${{ contains(inputs.name, 'Node') }}
      run: |
        npm install -g turbo
        npm install -g nx

    - name: Login to docker
      uses: docker/login-action@v3
      # only run if there was a docker-username and password provided
      # this is because builds from forks will not have access to secrets
      # and we don't want to fail the workflow if they don't have access to secrets
      if: ${{ inputs.docker-username != '' && inputs.docker-password != '' }}
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
        registry: ${{ inputs.docker-registry }}

    - uses: dapr/setup-dapr@v2
      name: Setup Dapr
      if: ${{ contains(inputs.name, 'Dapr') }}
      with:
        version: ${{ env.DAPR_VERSION }}

    - name: Init Dapr
      shell: bash
      if: ${{ matrix.os == 'ubuntu-latest' && contains(inputs.name, 'Dapr') }}
      run: |
        dapr init --runtime-version=${{ env.DAPR_VERSION }}
        dapr --version

    - uses: ai-action/setup-ollama@v1
      name: Setup Ollama
      if: ${{ inputs.name == 'Full' || contains(inputs.name, 'Hosting.Ollama') }}
      with:
        version: 0.11.8
