using Aspire.Hosting.ApplicationModel;
using CommunityToolkit.Aspire.Hosting.SeaweedFS;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Diagnostics.HealthChecks;

#pragma warning disable IDE0130
namespace Aspire.Hosting;
#pragma warning restore IDE0130

/// <summary>
/// Provides extension methods for adding SeaweedFS resources to an <see cref="IDistributedApplicationBuilder"/>.
/// </summary>
public static class SeaweedFSBuilderExtensions
{
    private const int DefaultS3Port = 8333;
    private const int DefaultMasterPort = 9333;
    private const int DefaultFilerPort = 8888;
    private const int DefaultVolumePort = 8080;

    private const string AccessKeyEnvVarName = "S3_ACCESS_KEY";
    private const string SecretKeyEnvVarName = "S3_SECRET_KEY";

    /// <summary>
    /// Adds a base SeaweedFS container (Master and Volume APIs) to the application model.
    /// Chain with .WithS3() or .WithFiler() to enable additional APIs.
    /// </summary>
    /// <param name="builder">The <see cref="IDistributedApplicationBuilder"/>.</param>
    /// <param name="name">The name of the resource. This name will be used as the connection string name when referenced in a dependency.</param>
    /// <returns>A reference to the <see cref="IResourceBuilder{SeaweedFSContainerResource}"/>.</returns>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> AddSeaweedFS(
        this IDistributedApplicationBuilder builder,
        [ResourceName] string name)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrEmpty(name);

        // Properly name the access key to avoid collisions and explicitly add it to the builder 
        // so it appears in the manifest generated by azd.
        ParameterResource accessKeyParameter = new($"{name}-accessKey", _ => "admin");
        builder.AddResource(accessKeyParameter);

        ParameterResource secretKeyParameter = ParameterResourceBuilderExtensions.CreateDefaultPasswordParameter(builder, $"{name}-secretKey");

        SeaweedFSContainerResource resource = new(name, accessKeyParameter, secretKeyParameter);

        IResourceBuilder<SeaweedFSContainerResource> builderWithResource = builder.AddResource(resource)
            .WithImage(SeaweedFSContainerImageTags.Image, SeaweedFSContainerImageTags.Tag)
            .WithImageRegistry(SeaweedFSContainerImageTags.Registry)
            .WithHttpEndpoint(targetPort: DefaultMasterPort, name: SeaweedFSContainerResource.MasterEndpointName)
            .WithHttpEndpoint(targetPort: DefaultVolumePort, name: SeaweedFSContainerResource.VolumeEndpointName);

        // Configure strict, topology-aware readiness verification
        string healthCheckKey = $"{name}_check";
        builder.Services.AddHealthChecks()
            .Add(new HealthCheckRegistration(
                name: healthCheckKey,
                factory: sp => new SeaweedFSHealthCheck(resource),
                failureStatus: HealthStatus.Unhealthy,
                tags: ["seaweedfs", "storage", "cluster"],
                timeout: TimeSpan.FromSeconds(10)));

        builderWithResource.WithHealthCheck(healthCheckKey);

        // Core pipeline arguments map
        builderWithResource.WithArgs(context =>
        {
            bool isFilerEnabled = builderWithResource.Resource.Annotations.OfType<SeaweedFSFilerAnnotation>().Any();
            bool isS3Enabled = builderWithResource.Resource.Annotations.OfType<SeaweedFSS3Annotation>().Any();
            SeaweedFSCustomS3ConfigAnnotation? customConfig = builderWithResource.Resource.Annotations.OfType<SeaweedFSCustomS3ConfigAnnotation>().SingleOrDefault();

            if (isS3Enabled && !isFilerEnabled)
            {
                isFilerEnabled = true;
            }

            string args = "weed server -dir=\"/data\"";
            if (isFilerEnabled) args += " -filer";

            if (customConfig is not null)
            {
                args += " -s3 -s3.config=\"/etc/seaweedfs/s3-custom.json\"";
                context.Args.Clear();
                context.Args.Add("server");
                context.Args.Add("-dir=/data");
                context.Args.Add("-s3");
                context.Args.Add("-s3.config=/etc/seaweedfs/s3-custom.json");
                context.Args.Add("-filer");
            }
            else if (isS3Enabled)
            {
                args += " -s3 -s3.config=\"/tmp/s3.json\"";

                // Robust shell script escaping using 'EOF' Heredoc to avoid escaping breakages
                string shellScript = "cat << EOF > /tmp/s3.json\n" +
                                  "{\"identities\":[{\"name\":\"aspire-user\",\"credentials\":[{\"accessKey\":\"" + $"${AccessKeyEnvVarName}" + "\",\"secretKey\":\"" + $"${SecretKeyEnvVarName}" + "\"}],\"actions\":[\"Admin\",\"Read\",\"Write\",\"List\",\"Tagging\"]}]}\n" +
                                  "EOF\n" +
                                  $"exec {args}";

                context.Args.Clear();
                context.Args.Add("-c");
                context.Args.Add(shellScript);
            }
            else
            {
                context.Args.Clear();
                context.Args.Add("server");
                context.Args.Add("-dir=/data");
                if (isFilerEnabled) context.Args.Add("-filer");
            }
        });

        return builderWithResource;
    }

    /// <summary>
    /// Enables the SeaweedFS S3-Compatible API Gateway.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithS3(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        int? s3Port = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        // Implicitly expose the Filer endpoint since the S3 gateway relies on it natively.
        // This ensures the endpoint is registered in the Aspire application model.
        if (!builder.Resource.Annotations.OfType<SeaweedFSFilerAnnotation>().Any())
        {
            builder.WithFiler();
        }

        builder.WithAnnotation(new SeaweedFSS3Annotation());
        builder.WithHttpEndpoint(targetPort: DefaultS3Port, port: s3Port, name: SeaweedFSContainerResource.S3EndpointName);

        // Ensure implicit initialization of entrypoint behavior based on the required shell deployment
        builder.WithEntrypoint("sh");

        builder.WithEnvironment(AccessKeyEnvVarName, builder.Resource.AccessKey);
        builder.WithEnvironment(SecretKeyEnvVarName, builder.Resource.SecretKey);

        return builder;
    }

    /// <summary>
    /// Enables the SeaweedFS Native Filer API.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithFiler(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        int? filerPort = null)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder.WithAnnotation(new SeaweedFSFilerAnnotation());
        builder.WithHttpEndpoint(targetPort: DefaultFilerPort, port: filerPort, name: SeaweedFSContainerResource.FilerEndpointName);

        if (!builder.Resource.Annotations.OfType<SeaweedFSS3Annotation>().Any())
        {
            builder.WithEntrypoint("weed");
        }

        return builder;
    }

    /// <summary>
    /// Configures the Master API host port that the SeaweedFS resource is exposed on.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithHostPort(this IResourceBuilder<SeaweedFSContainerResource> builder, int? port)
    {
        ArgumentNullException.ThrowIfNull(builder);

        return builder.WithEndpoint(SeaweedFSContainerResource.MasterEndpointName, endpoint =>
        {
            endpoint.Port = port;
        });
    }

    /// <summary>
    /// Configures the Access Key that the SeaweedFS S3 resource uses.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithAccessKey(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        IResourceBuilder<ParameterResource> accessKey)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(accessKey);

        builder.Resource.AccessKey = accessKey.Resource;
        return builder;
    }

    /// <summary>
    /// Configures the Secret Key that the SeaweedFS S3 resource uses.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithSecretKey(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        IResourceBuilder<ParameterResource> secretKey)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(secretKey);

        builder.Resource.SecretKey = secretKey.Resource;
        return builder;
    }

    /// <summary>
    /// Configures the SeaweedFS S3 API to use a specific external security configuration file.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithS3ConfigFile(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        string configFilePath)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentException.ThrowIfNullOrWhiteSpace(configFilePath);

        // Prevent the container from enabling the -s3 arg without actually mapping the S3 port.
        if (!builder.Resource.Annotations.OfType<SeaweedFSS3Annotation>().Any())
        {
            throw new InvalidOperationException("You must enable the S3 Gateway using .WithS3() before configuring a custom S3 config file.");
        }

        string containerPath = "/etc/seaweedfs/s3-custom.json";

        // Safely annotate the pipeline to resolve logic within 'WithArgs' rather than forcing raw overrides
        builder.WithAnnotation(new SeaweedFSCustomS3ConfigAnnotation(configFilePath));
        builder.WithEntrypoint("weed");

        return builder.WithBindMount(configFilePath, containerPath, isReadOnly: true);
    }

    /// <summary>
    /// Adds a bind mount for the SeaweedFS data folder.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithDataBindMount(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        string source,
        bool isReadOnly = false)
    {
        ArgumentNullException.ThrowIfNull(builder);
        ArgumentNullException.ThrowIfNull(source);

        return builder.WithBindMount(source, "/data", isReadOnly);
    }

    /// <summary>
    /// Adds a named volume for the SeaweedFS data folder.
    /// </summary>
#pragma warning disable ASPIREATS001
    [AspireExport]
#pragma warning restore ASPIREATS001
    public static IResourceBuilder<SeaweedFSContainerResource> WithDataVolume(
        this IResourceBuilder<SeaweedFSContainerResource> builder,
        string? name = null,
        bool isReadOnly = false)
    {
        ArgumentNullException.ThrowIfNull(builder);

        string volumeName = name ?? VolumeNameGenerator.Generate(builder, "data");

        return builder.WithVolume(volumeName, "/data", isReadOnly);
    }
}