//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DbxBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DbxContainerResource> AddDbx(this IDistributedApplicationBuilder builder, string name = "dbx", int? port = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DbxContainerResource> WithHostPort(this ApplicationModel.IResourceBuilder<ApplicationModel.DbxContainerResource> builder, int? port) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public sealed partial class DbxConnectionConfig
    {
        [System.Text.Json.Serialization.JsonPropertyName("connection_string")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? ConnectionString { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("connect_timeout_secs")]
        public ulong ConnectTimeoutSecs { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("database")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? Database { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("db_type")]
        public required DbxDatabaseType DbType { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("host")]
        public required string Host { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("id")]
        public required string Id { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("jdbc_driver_class")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? JdbcDriverClass { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("jdbc_driver_paths")]
        public System.Collections.Generic.List<string> JdbcDriverPaths { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("name")]
        public required string Name { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("password")]
        public required string Password { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("port")]
        public required ushort Port { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("query_timeout_secs")]
        public ulong QueryTimeoutSecs { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_cluster_nodes")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisClusterNodes { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_connection_mode")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisConnectionMode { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_sentinel_master")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisSentinelMaster { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_sentinel_nodes")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisSentinelNodes { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_sentinel_password")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisSentinelPassword { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_sentinel_tls")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingDefault)]
        public bool RedisSentinelTls { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("redis_sentinel_username")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? RedisSentinelUsername { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("ssl")]
        public bool Ssl { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("url_params")]
        [System.Text.Json.Serialization.JsonIgnore(Condition = System.Text.Json.Serialization.JsonIgnoreCondition.WhenWritingNull)]
        public string? UrlParams { get { throw null; } set { } }

        [System.Text.Json.Serialization.JsonPropertyName("username")]
        public required string Username { get { throw null; } set { } }
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class DbxContainerResource : ContainerResource
    {
        public DbxContainerResource(string name) : base(default!, default) { }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public bool AddConnection(DbxConnectionConfig connection) { throw null; }
    }

    public enum DbxDatabaseType
    {
        Mysql = 0,
        Postgres = 1,
        Sqlite = 2,
        Redis = 3,
        DuckDb = 4,
        ClickHouse = 5,
        SqlServer = 6,
        MongoDb = 7,
        Oracle = 8,
        Elasticsearch = 9,
        Doris = 10,
        StarRocks = 11,
        Redshift = 12,
        Dameng = 13,
        Kingbase = 14,
        Highgo = 15,
        Vastbase = 16,
        Goldendb = 17,
        Gaussdb = 18,
        Yashandb = 19,
        Databricks = 20,
        SapHana = 21,
        Teradata = 22,
        Vertica = 23,
        Firebird = 24,
        Exasol = 25,
        OpenGauss = 26,
        OceanbaseOracle = 27,
        Gbase = 28,
        Access = 29,
        H2 = 30,
        Snowflake = 31,
        Trino = 32,
        Hive = 33,
        Db2 = 34,
        Informix = 35,
        Neo4j = 36,
        Cassandra = 37,
        Bigquery = 38,
        Kylin = 39,
        Sundb = 40,
        Tdengine = 41,
        Xugu = 42,
        Iris = 43,
        Jdbc = 44
    }
}