@CommunityToolkit.Aspire.Hosting.Keycloak.Extensions.Prod_HostAddress = http://localhost:5286

GET {{CommunityToolkit.Aspire.Hosting.Keycloak.Extensions.Prod_HostAddress}}/weatherforecast/
Accept: application/json

###
