//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class PerlAppResourceBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.PerlAppResource> AddPerlApi(this IDistributedApplicationBuilder builder, string resourceName, string appDirectory, string scriptName) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.PerlAppResource> AddPerlExecutable(this IDistributedApplicationBuilder builder, string resourceName, string appDirectory, string executablePath) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.PerlAppResource> AddPerlModule(this IDistributedApplicationBuilder builder, string resourceName, string appDirectory, string moduleName) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.PerlAppResource> AddPerlScript(this IDistributedApplicationBuilder builder, string resourceName, string appDirectory, string scriptName) { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithCarton<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder)
            where TResource : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithCpanMinus<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder)
            where TResource : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithLocalLib<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string path = "local")
            where TResource : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithPackage<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, string packageName, bool force = false, bool skipTest = false)
            where TResource : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<T> WithPerlbrew<T>(this ApplicationModel.IResourceBuilder<T> builder, string version, string? perlbrewRoot = null)
            where T : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<T> WithPerlbrewEnvironment<T>(this ApplicationModel.IResourceBuilder<T> builder, string version, string? perlbrewRoot = null)
            where T : ApplicationModel.PerlAppResource { throw null; }

        [System.Diagnostics.CodeAnalysis.Experimental("CTASPIREPERL001")]
        public static ApplicationModel.IResourceBuilder<TResource> WithPerlCertificateTrust<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder)
            where TResource : ApplicationModel.PerlAppResource { throw null; }

        public static ApplicationModel.IResourceBuilder<TResource> WithProjectDependencies<TResource>(this ApplicationModel.IResourceBuilder<TResource> builder, bool cartonDeployment = false)
            where TResource : ApplicationModel.PerlAppResource { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class PerlAppResource : ExecutableResource, IResourceWithServiceDiscovery, IResourceWithEndpoints, IResource
    {
        public PerlAppResource(string name, string executablePath, string appDirectory) : base(default!, default!, default!) { }
    }

    public partial class PerlModuleInstallerResource : ExecutableResource
    {
        public PerlModuleInstallerResource(string name, string packageManager, string workingDirectory) : base(default!, default!, default!) { }
    }
}

namespace CommunityToolkit.Aspire.Hosting.Perl
{
    public enum EntrypointType
    {
        Executable = 0,
        Script = 1,
        Module = 2,
        API = 3
    }

    public enum PerlPackageManager
    {
        Cpan = 0,
        Cpanm = 1,
        Carton = 2
    }

    public static partial class PerlPackageManagerExtensions
    {
        public static string ToExecutableName(this PerlPackageManager packageManager) { throw null; }
    }
}