//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class K3sBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> AddK3sCluster(this IDistributedApplicationBuilder builder, string name, int? apiServerPort = null, int? agentCount = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithAgentCount(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, int count) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string? name = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithDisabledComponent(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string component) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithExtraArg(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string arg) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithHelmImage(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string? tag = null, string? image = null, string? registry = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithK3sVersion(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string tag) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithKubectlImage(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string? tag = null, string? image = null, string? registry = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithLifetime(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, ApplicationModel.ContainerLifetime lifetime) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithPodSubnet(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string cidr) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> WithServiceSubnet(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string cidr) { throw null; }
    }

    public static partial class K3sHelmBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.HelmReleaseResource> AddHelmRelease(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string name, string chart, string? repo = null, string? version = null, string @namespace = "default") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.HelmReleaseResource> WithHelmValue(this ApplicationModel.IResourceBuilder<ApplicationModel.HelmReleaseResource> builder, string key, string value) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.HelmReleaseResource> WithHelmValuesFile(this ApplicationModel.IResourceBuilder<ApplicationModel.HelmReleaseResource> builder, string path) { throw null; }
    }

    public static partial class K3sManifestBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K8sManifestResource> AddK8sManifest(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string name, string path) { throw null; }
    }

    public static partial class K3sServiceEndpointExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K3sServiceEndpointResource> AddServiceEndpoint(this ApplicationModel.IResourceBuilder<ApplicationModel.K3sClusterResource> builder, string name, string serviceName, int servicePort, string @namespace = "default", string? scheme = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public sealed partial class HelmReleaseResource : ContainerResource, IResourceWithParent<K3sClusterResource>, IResourceWithParent, IResource
    {
        public HelmReleaseResource(string name, string releaseName, string @namespace, K3sClusterResource cluster) : base(default!, default) { }

        public string Namespace { get { throw null; } }

        public K3sClusterResource Parent { get { throw null; } }

        public string ReleaseName { get { throw null; } }
    }

    public sealed partial class K3sAgentResource : ContainerResource, IResourceWithParent<K3sClusterResource>, IResourceWithParent, IResource
    {
        public K3sAgentResource(string name, K3sClusterResource cluster) : base(default!, default) { }

        public K3sClusterResource Parent { get { throw null; } }
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class K3sClusterResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public K3sClusterResource(string name) : base(default!, default) { }

        public EndpointReference ApiEndpoint { get { throw null; } }

        public string? ConnectionStringEnvironmentVariable { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        [AspireExportIgnore(Reason = "Internal tracking collection; not needed by guest SDK consumers.")]
        public System.Collections.Generic.IReadOnlyDictionary<string, string> HelmReleases { get { throw null; } }

        [AspireExportIgnore(Reason = "Internal tracking collection; not needed by guest SDK consumers.")]
        public System.Collections.Generic.IReadOnlyList<string> Manifests { get { throw null; } }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class K3sServiceEndpointResource : Resource, IResourceWithParent<K3sClusterResource>, IResourceWithParent, IResource, IResourceWithWaitSupport, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public K3sServiceEndpointResource(string name, string serviceName, int servicePort, string @namespace, K3sClusterResource cluster) : base(default!) { }

        public string? ConnectionStringEnvironmentVariable { get { throw null; } }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public int HostPort { get { throw null; } }

        public string Namespace { get { throw null; } }

        public K3sClusterResource Parent { get { throw null; } }

        public string ServiceName { get { throw null; } }

        public int ServicePort { get { throw null; } }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class K8sManifestResource : ContainerResource, IResourceWithParent<K3sClusterResource>, IResourceWithParent, IResource
    {
        public K8sManifestResource(string name, string path, K3sClusterResource cluster) : base(default!, default) { }

        public K3sClusterResource Parent { get { throw null; } }

        public string Path { get { throw null; } }
    }
}

namespace CommunityToolkit.Aspire.Hosting
{
    public sealed partial class K3sClusterOptions
    {
        public int AgentCount { get { throw null; } set { } }

        public string? ClusterCidr { get { throw null; } set { } }

        public System.Collections.Generic.IList<string> DisabledComponents { get { throw null; } }

        public System.Collections.Generic.IList<string> ExtraArgs { get { throw null; } }

        public string HelmImage { get { throw null; } set { } }

        public string HelmRegistry { get { throw null; } set { } }

        public string HelmTag { get { throw null; } set { } }

        public string? ImageTag { get { throw null; } set { } }

        public string KubectlImage { get { throw null; } set { } }

        public string KubectlRegistry { get { throw null; } set { } }

        public string KubectlTag { get { throw null; } set { } }

        public string? ServiceCidr { get { throw null; } set { } }
    }
}