using System.Globalization;
using System.Text;

namespace CommunityToolkit.Aspire.Hosting.Compose.Generator;

/// <summary>
/// Generates C# source code for compose file wrapper classes.
/// </summary>
internal static class ComposeClassEmitter
{
    /// <summary>
    /// Emits a wrapper class with typed properties for each compose service.
    /// </summary>
    public static string EmitClass(string className, string composePath, string[] serviceNames)
    {
        string sanitizedClassName = SanitizeIdentifier(className);
        StringBuilder sb = new();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Compose");
        sb.AppendLine("{");

        sb.AppendLine("    /// <summary>");
        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "    /// Typed wrapper for compose file: {0}",
            EscapeXml(composePath)));
        sb.AppendLine("    /// </summary>");

        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "    [global::CommunityToolkit.Aspire.Hosting.Compose.ComposeReferencePath(@\"{0}\")]",
            composePath.Replace("\"", "\"\"")));
        sb.AppendLine("    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]");

        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "    public sealed class {0}", sanitizedClassName));
        sb.AppendLine("    {");

        sb.AppendLine("        private readonly global::CommunityToolkit.Aspire.Hosting.Compose.ComposeResourceCollection _inner;");
        sb.AppendLine();

        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "        /// <summary>Creates a new <see cref=\"{0}\"/> wrapping the given collection.</summary>",
            sanitizedClassName));
        sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
            "        public {0}(global::CommunityToolkit.Aspire.Hosting.Compose.ComposeResourceCollection inner) => _inner = inner;",
            sanitizedClassName));
        sb.AppendLine();

        foreach (string name in serviceNames)
        {
            string propName = SanitizeIdentifier(name);
            sb.AppendLine("        /// <summary>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "        /// Gets the resource builder for the <c>{0}</c> service.",
                EscapeXml(name)));
            sb.AppendLine("        /// </summary>");
            sb.AppendLine(string.Format(CultureInfo.InvariantCulture,
                "        public global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.ContainerResource> {0} => _inner[\"{1}\"];",
                propName, name.Replace("\"", "\\\"")));
            sb.AppendLine();
        }

        sb.AppendLine("        /// <summary>Gets a resource by service name.</summary>");
        sb.AppendLine("        public global::Aspire.Hosting.ApplicationModel.IResourceBuilder<global::Aspire.Hosting.ApplicationModel.ContainerResource> this[string serviceName] => _inner[serviceName];");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Converts a name like "my-postgres" or "my_infra" to a valid C# PascalCase identifier.
    /// </summary>
    internal static string SanitizeIdentifier(string name)
    {
        if (string.IsNullOrEmpty(name)) return "Unknown";

        StringBuilder sb = new();
        bool capitalizeNext = true;

        foreach (char ch in name)
        {
            if (ch is '-' or '_' or '.' or ' ')
            {
                capitalizeNext = true; 
                continue;
            }

            if (sb.Length == 0 && char.IsDigit(ch))
                sb.Append('_');

            sb.Append(capitalizeNext ? char.ToUpperInvariant(ch) : ch);
            capitalizeNext = false;
        }

        return sb.Length == 0 ? "Unknown" : sb.ToString();
    }

    private static string EscapeXml(string text)
    {
        return text
            .Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;");
    }
}
