services:
  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

  prometheus:
    image: prom/prometheus:v2.48.0
    ports:
      - "9090:9090"
    depends_on:
      - grafana
