//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class DuckDBResourceBuilderExtensions
    {
        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DuckDBResource> AddDuckDB(this IDistributedApplicationBuilder builder, string name, string? databasePath = null, string? databaseFileName = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.DuckDBResource> WithReadOnly(this ApplicationModel.IResourceBuilder<ApplicationModel.DuckDBResource> builder) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class DuckDBResource : Resource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public DuckDBResource(string name, string databasePath, string databaseFileName) : base(default!) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}