<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\examples\mosquitto\CommunityToolkit.Aspire.Hosting.Mosquitto.AppHost\CommunityToolkit.Aspire.Hosting.Mosquitto.AppHost.csproj" />
    <ProjectReference Include="..\..\src\CommunityToolkit.Aspire.Hosting.Mosquitto\CommunityToolkit.Aspire.Hosting.Mosquitto.csproj" />
    <ProjectReference Include="..\CommunityToolkit.Aspire.Testing\CommunityToolkit.Aspire.Testing.csproj" />
  </ItemGroup>

</Project>
