//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireSqliteExtensions
    {
        public static void AddKeyedSqliteConnection(this IHostApplicationBuilder builder, string name, System.Action<SqliteConnectionSettings>? configureSettings = null) { }

        public static void AddSqliteConnection(this IHostApplicationBuilder builder, string name, System.Action<SqliteConnectionSettings>? configureSettings = null) { }
    }

    public sealed partial class SqliteConnectionSettings
    {
        public string? ConnectionString { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }

        public System.Collections.Generic.IEnumerable<SqliteExtensionMetadata> Extensions { get { throw null; } set { } }
    }

    public partial record SqliteExtensionMetadata(string Extension, string? PackageName, bool IsNuGetPackage, string? ExtensionFolder)
    {
    }
}