//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class SurrealDbBuilderExtensions
    {
        [AspireExport("addDatabase", Description = "Adds a SurrealDB database resource to the application model")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbDatabaseResource> AddDatabase(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbNamespaceResource> builder, string name, string? databaseName = null) { throw null; }

        [AspireExport("addNamespace", Description = "Adds a SurrealDB namespace resource to the application model")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbNamespaceResource> AddNamespace(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder, string name, string? namespaceName = null) { throw null; }

        [AspireExport("addSurrealServer", Description = "Adds a SurrealDB server resource to the application model")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> AddSurrealServer(this IDistributedApplicationBuilder builder, string name, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? userName = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? password = null, int? port = null, string path = "memory", bool strictMode = false) { throw null; }

        [AspireExport("withDatabaseCreationScript", MethodName = "withCreationScript", Description = "Defines the SQL script used to create the database")]
        [System.Diagnostics.CodeAnalysis.Experimental("CTASPIRE002")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbDatabaseResource> WithCreationScript(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbDatabaseResource> builder, string script) { throw null; }

        [AspireExport("withNamespaceCreationScript", MethodName = "withCreationScript", Description = "Defines the SQL script used to create the namespace")]
        [System.Diagnostics.CodeAnalysis.Experimental("CTASPIRE002")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbNamespaceResource> WithCreationScript(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbNamespaceResource> builder, string script) { throw null; }

        [AspireExport("withDataBindMount", Description = "Adds a bind mount for the data folder to a SurrealDB resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder, string source) { throw null; }

        [AspireExport("withDataVolume", Description = "Adds a named volume for the data folder to a SurrealDB resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder, string? name = null) { throw null; }

        [AspireExport("withInitFiles", Description = "Copies init files into a SurrealDB container resource")]
        [System.Diagnostics.CodeAnalysis.Experimental("CTASPIRE002")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> WithInitFiles(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder, string source) { throw null; }

        [AspireExportIgnore(Reason = "Uses Microsoft.Extensions.Logging.LogLevel, which is not ATS-compatible. Use the exported string-based overload instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> WithLogLevel(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder, Microsoft.Extensions.Logging.LogLevel logLevel) { throw null; }

        [AspireExport("withSurrealDbOtlpExporter", MethodName = "withSurrealDbOtlpExporter", Description = "Configures the SurrealDB resource to export telemetry to the Aspire dashboard")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> WithOtlpExporter(this ApplicationModel.IResourceBuilder<ApplicationModel.SurrealDbServerResource> builder) { throw null; }

        [AspireExportIgnore(Reason = "Uses Action<IResourceBuilder<SurrealistContainerResource>>, which is not ATS-compatible. Use the exported overload instead.")]
        public static ApplicationModel.IResourceBuilder<T> WithSurrealist<T>(this ApplicationModel.IResourceBuilder<T> builder, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.SurrealistContainerResource>>? configureContainer = null, string? containerName = null)
            where T : ApplicationModel.SurrealDbServerResource { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class SurrealDbDatabaseResource : Resource, IResourceWithParent<SurrealDbNamespaceResource>, IResourceWithParent, IResource, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public SurrealDbDatabaseResource(string name, string databaseName, SurrealDbNamespaceResource parent) : base(default!) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string DatabaseName { get { throw null; } }

        public SurrealDbNamespaceResource Parent { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class SurrealDbNamespaceResource : Resource, IResourceWithParent<SurrealDbServerResource>, IResourceWithParent, IResource, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public SurrealDbNamespaceResource(string name, string namespaceName, SurrealDbServerResource parent) : base(default!) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string> Databases { get { throw null; } }

        public string NamespaceName { get { throw null; } }

        public SurrealDbServerResource Parent { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }

    [AspireExport(ExposeProperties = true)]
    public partial class SurrealDbServerResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public SurrealDbServerResource(string name, ParameterResource? userName, ParameterResource password) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public System.Collections.Generic.IReadOnlyDictionary<string, string> Namespaces { get { throw null; } }

        public ParameterResource PasswordParameter { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        public ParameterResource? UserNameParameter { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }

        public System.Threading.Tasks.ValueTask<string?> GetConnectionStringAsync(System.Threading.CancellationToken cancellationToken = default) { throw null; }
    }

    public sealed partial class SurrealistContainerResource : ContainerResource
    {
        public SurrealistContainerResource(string name) : base(default!, default) { }
    }
}