//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.SurrealDb
{
    public sealed partial class SurrealDbClientSettings
    {
        public bool DisableHealthChecks { get { throw null; } set { } }

        public int? HealthCheckTimeout { get { throw null; } set { } }

        public Microsoft.Extensions.DependencyInjection.ServiceLifetime Lifetime { get { throw null; } set { } }

        public Microsoft.Extensions.DependencyInjection.SurrealDbOptions? Options { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireSurrealDbExtensions
    {
        public static void AddKeyedSurrealClient(this IHostApplicationBuilder builder, string name, System.Action<CommunityToolkit.Aspire.SurrealDb.SurrealDbClientSettings>? configureSettings = null) { }

        public static void AddSurrealClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.SurrealDb.SurrealDbClientSettings>? configureSettings = null) { }
    }
}