//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Extensions.Hosting
{
    public static partial class AspireDuckDBExtensions
    {
        public static void AddDuckDBConnection(this IHostApplicationBuilder builder, string name, System.Action<DuckDBConnectionSettings>? configureSettings = null) { }

        public static void AddKeyedDuckDBConnection(this IHostApplicationBuilder builder, string name, System.Action<DuckDBConnectionSettings>? configureSettings = null) { }
    }

    public sealed partial class DuckDBConnectionSettings
    {
        public string? ConnectionString { get { throw null; } set { } }

        public bool DisableHealthChecks { get { throw null; } set { } }
    }
}