<Project Sdk="Aspire.AppHost.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Aspire.Hosting.Azure.Storage" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\src\CommunityToolkit.Aspire.Hosting.Azure.Extensions\CommunityToolkit.Aspire.Hosting.Azure.Extensions.csproj" IsAspireProjectResource="false" />
    </ItemGroup>

</Project>
