//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class K6BuilderExtensions
    {
        [AspireExport("addK6", Description = "Adds a Grafana k6 container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K6Resource> AddK6(this IDistributedApplicationBuilder builder, string name, bool enableBrowserExtensions = false, int? port = null) { throw null; }

        [AspireExport("withK6OtlpEnvironment", Description = "Sets K6 OTEL environment variables from the existing OTEL environment for this resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K6Resource> WithK6OtlpEnvironment(this ApplicationModel.IResourceBuilder<ApplicationModel.K6Resource> builder) { throw null; }

        [AspireExport("withScript", Description = "Runs a k6 script when starting the Grafana k6 container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.K6Resource> WithScript(this ApplicationModel.IResourceBuilder<ApplicationModel.K6Resource> builder, string scriptPath, int virtualUsers = 10, string duration = "30s") { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class K6Resource : ContainerResource
    {
        public K6Resource(string name) : base(default!, default) { }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}