//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class AzureBlobStorageResourceBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<Azure.AzureBlobStorageResource> WithAzureStorageExplorer(this ApplicationModel.IResourceBuilder<Azure.AzureBlobStorageResource> blobs, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.AzureStorageExplorerResource>>? configureContainer = null, string? name = null) { throw null; }
    }

    public static partial class AzureQueueStorageResourceBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<Azure.AzureQueueStorageResource> WithAzureStorageExplorer(this ApplicationModel.IResourceBuilder<Azure.AzureQueueStorageResource> queues, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.AzureStorageExplorerResource>>? configureContainer = null, string? name = null) { throw null; }
    }

    public static partial class AzureStorageExplorerBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.AzureStorageExplorerResource> WithHostPort(this ApplicationModel.IResourceBuilder<ApplicationModel.AzureStorageExplorerResource> builder, int? port) { throw null; }
    }

    public static partial class AzureTableStorageResourceBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<Azure.AzureTableStorageResource> WithAzureStorageExplorer(this ApplicationModel.IResourceBuilder<Azure.AzureTableStorageResource> tables, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.AzureStorageExplorerResource>>? configureContainer = null, string? name = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class AzureStorageExplorerResource : ContainerResource
    {
        public AzureStorageExplorerResource(string name) : base(default!, default) { }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}