//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CommunityToolkit.Aspire.OllamaSharp
{
    public sealed partial class OllamaSharpSettings
    {
        public bool DisableHealthChecks { get { throw null; } set { } }

        public System.Uri? Endpoint { get { throw null; } set { } }

        public int? HealthCheckTimeout { get { throw null; } set { } }

        public System.Collections.Generic.IReadOnlyList<string> Models { get { throw null; } set { } }

        public string? SelectedModel { get { throw null; } set { } }
    }
}

namespace Microsoft.Extensions.Hosting
{
    public partial class AspireOllamaApiClientBuilder
    {
        public AspireOllamaApiClientBuilder(IHostApplicationBuilder hostBuilder, string serviceKey, bool disableTracing) { }

        public bool DisableTracing { get { throw null; } }

        public IHostApplicationBuilder HostBuilder { get { throw null; } }

        public string ServiceKey { get { throw null; } }
    }

    public static partial class AspireOllamaChatClientExtensions
    {
        public static AI.ChatClientBuilder AddChatClient(this AspireOllamaApiClientBuilder builder) { throw null; }

        public static AI.ChatClientBuilder AddKeyedChatClient(this AspireOllamaApiClientBuilder builder) { throw null; }
    }

    public static partial class AspireOllamaEmbeddingGeneratorExtensions
    {
        public static AI.EmbeddingGeneratorBuilder<string, AI.Embedding<float>> AddEmbeddingGenerator(this AspireOllamaApiClientBuilder builder) { throw null; }

        public static AI.EmbeddingGeneratorBuilder<string, AI.Embedding<float>> AddKeyedEmbeddingGenerator(this AspireOllamaApiClientBuilder builder) { throw null; }
    }

    public static partial class AspireOllamaSharpExtensions
    {
        public static AspireOllamaApiClientBuilder AddKeyedOllamaApiClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { throw null; }

        [System.Obsolete("This approach to registering IChatClient is deprecated, use AddKeyedOllamaApiClient().AddChatClient() instead.")]
        public static void AddKeyedOllamaSharpChatClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { }

        [System.Obsolete("This approach to registering IEmbeddingGenerator is deprecated, use AddKeyedOllamaApiClient().AddEmbeddingGenerator() instead.")]
        public static void AddKeyedOllamaSharpEmbeddingGenerator(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { }

        public static AspireOllamaApiClientBuilder AddOllamaApiClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { throw null; }

        [System.Obsolete("This approach to registering IChatClient is deprecated, use AddOllamaApiClient().AddChatClient() instead.")]
        public static void AddOllamaSharpChatClient(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { }

        [System.Obsolete("This approach to registering IEmbeddingGenerator is deprecated, use AddOllamaApiClient().AddEmbeddingGenerator() instead.")]
        public static void AddOllamaSharpEmbeddingGenerator(this IHostApplicationBuilder builder, string connectionName, System.Action<CommunityToolkit.Aspire.OllamaSharp.OllamaSharpSettings>? configureSettings = null) { }
    }
}