//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class KeycloakPostgresExtension
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KeycloakResource> WithPostgres(this ApplicationModel.IResourceBuilder<ApplicationModel.KeycloakResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.PostgresDatabaseResource> database, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? username = null, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource>? password = null, bool xaEnabled = false) { throw null; }
    }
}