//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class GoFeatureFlagBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> AddGoFeatureFlag(this IDistributedApplicationBuilder builder, string name, string? pathToConfigFile = null, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> builder, string? name = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> WithGoffBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> builder, string source) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class GoFeatureFlagResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public GoFeatureFlagResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}