//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class GoFeatureFlagBuilderExtensions
    {
        [AspireExport("addGoFeatureFlag", Description = "Adds a GO Feature Flag container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> AddGoFeatureFlag(this IDistributedApplicationBuilder builder, string name, string? pathToConfigFile = null, int? port = null) { throw null; }

        [AspireExport("withDataVolume", Description = "Adds a named volume for the data folder to a GO Feature Flag container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> builder, string? name = null) { throw null; }

        [AspireExport("withGoffBindMount", Description = "Adds a bind mount for the GO Feature Flag configuration folder to a GO Feature Flag container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> WithGoffBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> builder, string source) { throw null; }

        [AspireExportIgnore(Reason = "LogLevel is defined in Microsoft.Extensions.Logging and is not ATS-compatible. Use the enum-based overload instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> WithLogLevel(this ApplicationModel.IResourceBuilder<ApplicationModel.GoFeatureFlagResource> builder, Microsoft.Extensions.Logging.LogLevel logLevel) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class GoFeatureFlagResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public GoFeatureFlagResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}