//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public enum StableDiffusionCppImageVariant
    {
        Cuda = 0,
        CudaSpark = 1,
        Vulkan = 2,
        Sycl = 3,
        Musa = 4
    }

    public static partial class StableDiffusionCppResourceBuilderExtensions
    {
        [AspireExport("addNamedHuggingFaceModel")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppModelResource> AddHuggingFaceModel(this ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> builder, string name, string repository, string fileName, string revision = "main") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppModelResource> AddHuggingFaceModel(this ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> builder, string repository, string fileName, string revision = "main") { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> AddStableDiffusionCpp(this IDistributedApplicationBuilder builder, string name, StableDiffusionCppImageVariant imageVariant = StableDiffusionCppImageVariant.Cuda, int? port = null, string? modelsDirectory = null) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> WithGPUSupport(this ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> builder) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> WithHuggingFaceToken(this ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> builder, ApplicationModel.IResourceBuilder<ApplicationModel.ParameterResource> token) { throw null; }

        [AspireExport]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> WithVaeTiling(this ApplicationModel.IResourceBuilder<ApplicationModel.StableDiffusionCppResource> builder) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public sealed partial class StableDiffusionCppModelResource : Resource, IResourceWithParent<StableDiffusionCppResource>, IResourceWithParent, IResource, IResourceWithConnectionString, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public StableDiffusionCppModelResource(string name, string repository, string fileName, string revision, StableDiffusionCppResource parent) : base(default!) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public string FileName { get { throw null; } }

        public StableDiffusionCppResource Parent { get { throw null; } }

        public string Repository { get { throw null; } }

        public string Revision { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }

    [AspireExport(ExposeProperties = true)]
    public sealed partial class StableDiffusionCppResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public StableDiffusionCppResource(string name, StableDiffusionCppImageVariant imageVariant, string modelsDirectory, string outputDirectory) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public StableDiffusionCppImageVariant ImageVariant { get { throw null; } }

        public StableDiffusionCppModelResource? Model { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}