//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class MongoDBBuilderExtensions
    {
        [AspireExportIgnore(Reason = "The configuration callback depends on DbGate container APIs that are not exported to polyglot app hosts. Use the overload without a configuration callback instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.MongoDBServerResource> WithDbGate(this ApplicationModel.IResourceBuilder<ApplicationModel.MongoDBServerResource> builder, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DbGateContainerResource>>? configureContainer = null, string? containerName = null) { throw null; }

        [AspireExportIgnore(Reason = "Action<IResourceBuilder<DbxContainerResource>> is not supported reliably in polyglot app hosts. Use the container options overload instead.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.MongoDBServerResource> WithDbx(this ApplicationModel.IResourceBuilder<ApplicationModel.MongoDBServerResource> builder, System.Action<ApplicationModel.IResourceBuilder<ApplicationModel.DbxContainerResource>>? configureContainer = null, string? containerName = null) { throw null; }
    }
}