//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class KurrentDBBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.KurrentDBResource> AddKurrentDB(this IDistributedApplicationBuilder builder, string name, int? port = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.KurrentDBResource> WithDataBindMount(this ApplicationModel.IResourceBuilder<ApplicationModel.KurrentDBResource> builder, string source) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.KurrentDBResource> WithDataVolume(this ApplicationModel.IResourceBuilder<ApplicationModel.KurrentDBResource> builder, string? name = null) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class KurrentDBResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public KurrentDBResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}

namespace CommunityToolkit.Aspire.Hosting.KurrentDB
{
    public partial class KurrentDBHealthCheck : Microsoft.Extensions.Diagnostics.HealthChecks.IHealthCheck, System.IDisposable
    {
        public KurrentDBHealthCheck(string connectionString) { }

        public System.Threading.Tasks.Task<Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckResult> CheckHealthAsync(Microsoft.Extensions.Diagnostics.HealthChecks.HealthCheckContext context, System.Threading.CancellationToken cancellationToken = default) { throw null; }

        public virtual void Dispose() { }
    }
}