//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class FlagdBuilderExtensions
    {
        [AspireExport("addFlagd", Description = "Adds a flagd container resource")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> AddFlagd(this IDistributedApplicationBuilder builder, string name, int? port = null, int? ofrepPort = null) { throw null; }

        [AspireExport("withBindFileSync", Description = "Configures flagd to use a bind-mounted flag configuration file")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> WithBindFileSync(this ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> builder, string fileSource, string filename = "flagd.json") { throw null; }

        [AspireExportIgnore(Reason = "Microsoft.Extensions.Logging.LogLevel is defined in an external assembly and is not compatible with ATS.")]
        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> WithLogLevel(this ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> builder, Microsoft.Extensions.Logging.LogLevel logLevel) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    [AspireExport(ExposeProperties = true)]
    public partial class FlagdResource : ContainerResource, IResourceWithConnectionString, IResource, IExpressionValue, IValueProvider, IManifestExpressionProvider, IValueWithReferences
    {
        public FlagdResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReference HealthCheckEndpoint { get { throw null; } }

        public EndpointReferenceExpression Host { get { throw null; } }

        public EndpointReference OfrepEndpoint { get { throw null; } }

        public EndpointReferenceExpression Port { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }

        public ReferenceExpression UriExpression { get { throw null; } }

        System.Collections.Generic.IEnumerable<System.Collections.Generic.KeyValuePair<string, ReferenceExpression>> IResourceWithConnectionString.GetConnectionProperties() { throw null; }
    }
}