//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Aspire.Hosting
{
    public static partial class FlagdBuilderExtensions
    {
        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> AddFlagd(this IDistributedApplicationBuilder builder, string name, int? port = null, int? ofrepPort = null) { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> WithBindFileSync(this ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> builder, string fileSource, string filename = "flagd.json") { throw null; }

        public static ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> WithLogLevel(this ApplicationModel.IResourceBuilder<ApplicationModel.FlagdResource> builder, Microsoft.Extensions.Logging.LogLevel logLevel) { throw null; }
    }
}

namespace Aspire.Hosting.ApplicationModel
{
    public partial class FlagdResource : ContainerResource, IResourceWithConnectionString, IResource, IManifestExpressionProvider, IValueProvider, IValueWithReferences
    {
        public FlagdResource(string name) : base(default!, default) { }

        public ReferenceExpression ConnectionStringExpression { get { throw null; } }

        public EndpointReference HealthCheckEndpoint { get { throw null; } }

        public EndpointReference OfrepEndpoint { get { throw null; } }

        public EndpointReference PrimaryEndpoint { get { throw null; } }
    }
}