name: Verify Test List

on:
  pull_request:

jobs:
  verify-test-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate test list
        run: bash eng/testing/generate-test-list-for-workflow.sh > generated-test-list.txt

      - name: Verify test list
        run: |
          diff -u <(grep -oP '(?<=name: \[)[^\]]+' .github/workflows/tests.yaml | tr ',' '\n' | sort) <(sort generated-test-list.txt) || exit 1
